### ISSUE TITLE
Need to be specific about Core 0.15.0 vs 0.15.1

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#1021]
We need to watch out for 0.15.1, possibly document (if we don't want to make changes) that only 0.15.0.x is supported at the moment.
```
[2017-11-18 15:43:42][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 11, in <module>
    load_entry_point('counterparty-cli==1.1.3', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/server.py", line 159, in main
    server.start_all(db)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/server.py", line 422, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/lib/blocks.py", line 1184, in follow
    txhash_list, raw_transactions = backend.get_tx_list(block)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/lib/backend/__init__.py", line 118, in get_tx_list
    tx_hash = bitcoinlib.core.b2lx(ctx.GetHash())
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/__init__.py", line 363, in GetHash
    raise AttributeError("CTransaction.GetHash() has been removed; use GetTxid() instead")
AttributeError: CTransaction.GetHash() has been removed; use GetTxid() instead
root@indexd:~# bitcoin-cli --version
Bitcoin Core RPC client version v0.15.1.0-gf518d9ae6aa
```

**Comment by unsystemizer** [comment]
Upon closer inspection, I realized my config files were probably correct - what unexpectedly fails is `pip3 install -r requirements`. I end up with the old python-bitcoinlib 0.8.0 due to this issue.

```
  Cloning https://github.com/petertodd/python-bitcoinlib.git (to 98676f981bf14a6a3a8313e762161cc289043b58) to /tmp/pip-build-u1ac4y0z/python-bitcoinlib-0.8.1
  Could not find a tag or branch '98676f981bf14a6a3a8313e762161cc289043b58', assuming commit.
  Running setup.py (path:/tmp/pip-build-u1ac4y0z/python-bitcoinlib-0.8.1/setup.py) egg_info for package python-bitcoinlib-0.8.1 produced metadata for project name python-bitcoinlib. Fix your #egg=python-bitcoinlib-0.8.1 fragments.
```

**Comment by chiguireitor** [comment]
Needs update to latest 0.10.1

**Comment by adamkrellenstein** [comment]
Fixed
