### ISSUE TITLE
Testnet SanityError

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-lib#1032]
Similar to Issue #615

Testnet keeps failing due to an unhandled exception 

```
counterparty-testnet_1   | [2018-04-29 20:42:05][INFO] Block: 1295286 (0.21s, hashes: L:0ffa4 / TX:62df3 / M:265ed)
counterparty-testnet_1   | [2018-04-29 20:42:06][ERROR] Unhandled Exception
counterparty-testnet_1   | Traceback (most recent call last):
counterparty-testnet_1   |   File "/usr/local/bin/counterparty-server", line 9, in <module>
counterparty-testnet_1   |     load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
counterparty-testnet_1   |   File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
counterparty-testnet_1   |     server.main()
counterparty-testnet_1   |   File "/counterparty-cli/counterpartycli/server.py", line 157, in main
counterparty-testnet_1   |     server.start_all(db)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/server.py", line 406, in start_all
counterparty-testnet_1   |     blocks.follow(db)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1214, in follow
counterparty-testnet_1   |     check.asset_conservation(db)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/check.py", line 139, in asset_conservation
counterparty-testnet_1   |     raise SanityError('{} {} issued ≠ {} {} held'.format(util.value_out(db, asset_issued, asset), asset, util.value_out(db, asset_held, asset), asset))
counterparty-testnet_1   | counterpartylib.lib.check.SanityError: 543175.62305568 XCP issued ≠ 543175.38062063 XCP held
```

**Comment by droplister** [comment]
I am closing this issue. I restarted the counterparty-testnet service today and it was able to parse past this block without issue. Seemingly temporary and likely not reproducible for testing.

**Comment by droplister** [comment]
Actually, it just failed again. I will try a reparse now and report back.

```
counterparty-testnet_1   | [2018-05-03 04:43:30][INFO] Block: 1296008 (0.25s, hashes: L:5e6a2 / TX:88989 / M:40c34)
counterparty-testnet_1   | [2018-05-03 04:43:30][INFO] Block: 1296009 (0.23s, hashes: L:4fd5d / TX:63a96 / M:39c75)
counterparty-testnet_1   | [2018-05-03 04:43:31][INFO] Block: 1296010 (0.26s, hashes: L:8295f / TX:21153 / M:a145b)
counterparty-testnet_1   | [2018-05-03 04:43:32][ERROR] Unhandled Exception
counterparty-testnet_1   | Traceback (most recent call last):
counterparty-testnet_1   |   File "/usr/local/bin/counterparty-server", line 9, in <module>
counterparty-testnet_1   |     load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
counterparty-testnet_1   |   File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
counterparty-testnet_1   |     server.main()
counterparty-testnet_1   |   File "/counterparty-cli/counterpartycli/server.py", line 157, in main
counterparty-testnet_1   |     server.start_all(db)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/server.py", line 406, in start_all
counterparty-testnet_1   |     blocks.follow(db)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1214, in follow
counterparty-testnet_1   |     check.asset_conservation(db)
counterparty-testnet_1   |   File "/counterparty-lib/counterpartylib/lib/check.py", line 139, in asset_conservation
counterparty-testnet_1   |     raise SanityError('{} {} issued ≠ {} {} held'.format(util.value_out(db, asset_issued, asset), asset, util.value_out(db, asset_held, asset), asset))
counterparty-testnet_1   | counterpartylib.lib.check.SanityError: 543172.12305568 XCP issued ≠ 543171.88062063 XCP held
federatednode_counterparty-testnet_1 exited with code 0
```

**Comment by droplister** [comment]
OK - If anyone encounters this in the future, run a reparse.

```
counterparty-testnet_1   | [2018-05-03 05:06:20][INFO] Running v1.1.3 of counterparty-server.
counterparty-testnet_1   | [2018-05-03 05:06:20][INFO] Running v9.55.4 of counterparty-lib.
counterparty-testnet_1   | [2018-05-03 05:06:20][INFO] Acquiring lock.
counterparty-testnet_1   | [2018-05-03 05:06:20][INFO] Connecting to database.
counterparty-testnet_1   | [2018-05-03 05:06:35][INFO] Connecting to backend.
counterparty-testnet_1   | [2018-05-03 05:06:35][INFO] Starting API Server.
counterparty-testnet_1   | [2018-05-03 05:06:49][INFO] Resuming parsing.
counterparty-testnet_1   | [2018-05-03 05:06:49][INFO] Block: 1296012 (0.30s, hashes: L:b855a / TX:9c303 / M:85deb)
counterparty-testnet_1   | [2018-05-03 05:06:49][INFO] Block: 1296013 (0.45s, hashes: L:2aaf5 / TX:696bf / M:75ff3)
counterparty-testnet_1   | [2018-05-03 05:06:49][INFO] Mempool cache initialized: 0.02s for 45 transactions
counterparty-testnet_1   | [2018-05-03 05:06:49][INFO] Ready for queries.
```
