### ISSUE TITLE
Counterparty Server Crash "Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by devinjdawson** [CounterpartyXCP/counterparty-lib#1033]
```
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 11, in <module>
    load_entry_point('counterparty-cli==1.1.3', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/server.py", line 157, in main
    server.start_all(db)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/server.py", line 408, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/lib/blocks.py", line 1149, in follow
    current_hash = backend.getblockhash(current_index)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/lib/backend/__init__.py", line 45, in getblockhash
    return BACKEND().getblockhash(blockcount)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/lib/backend/addrindex.py", line 226, in getblockhash
    return rpc('getblockhash', [blockcount])
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/lib/backend/addrindex.py", line 77, in rpc
    return rpc_call(payload)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/lib/backend/addrindex.py", line 52, in rpc_call
    response_json = response.json()
  File "/usr/local/lib/python3.5/dist-packages/requests-2.10.0-py3.5.egg/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Runs fine for about 5-10 minutes and then I get this error.
Ubuntu 16.04
The same issue occurs with default version requests-2.18.4

**Comment by jdogresorg** [comment]
Looks like the core issue is a failed 'getblockhash' call to bitcoind... and Counterparty just handling to the null/empty response from bitcoind.

Is your Bitcoind and Counterpartyd fully synced?  Do you get this error when parsing every new block, or just periodically?

**Comment by devinjdawson** [comment]
Waiting for the bitcoind server to reindex seemed to fix the issue. Thanks.
