### ISSUE TITLE
Counterparty-server returns HTTP 500 for get_assets REST API

### ISSUE THREAD

**Issue by koustubh25** [CounterpartyXCP/counterparty-lib#1046]
On Kubernetes, the liveness probe fails with the following error

```
[10.0.2.1 - - [10/Oct/2018 04:17:31] "GET /rest/assets/get HTTP/1.1" 500 -
Exception on /rest/assets/get [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_httpauth.py", line 88, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/lib/api.py", line 813, in handle_root
    response = handle_rest(rest_path, flask.request)
  File "/usr/local/lib/python3.5/dist-packages/counterparty_lib-9.55.4-py3.5.egg/counterpartylib/lib/api.py", line 935, in handle_rest
    file_format = flask_request.headers['Accept']
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/datastructures.py", line 1354, in __getitem__
    return _unicodify_header_value(self.environ['HTTP_' + key])
KeyError: 'HTTP_ACCEPT'
10.0.2.1 - - [10/Oct/2018 04:17:43] "GET /rest/assets/get HTTP/1.1" 500 -](url)
```
If I execute the same API using curl like this 
`curl http://username:password@localhost/rest/assets/get` it works and http response status is 200
I am not able to understand, why the same api fails with the above error on Kubernetes.
Judging from the logs above, is anything missing in the request?

**Comment by koustubh25** [comment]
Sorry, I was missing the `Accept` header. Closing this issue.
