### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/counterparty-lib#1060]
Hi, i got this error when running CP node

[2019-10-18 08:39:47][INFO] Running v1.1.4 of counterparty-server.
[2019-10-18 08:39:47][INFO] Running v9.56.0 of counterparty-lib.
[2019-10-18 08:39:47][INFO] Acquiring lock.
[2019-10-18 08:39:47][INFO] Connecting to database (SQLite 3.24.0-r1).

```
Traceback (most recent call last):
  File "/counterparty-lib/counterpartylib/lib/script.py", line 202, in test_array
    signatures_required, signatures_possible = int(signatures_required), int(signatures_possible)
ValueError: invalid literal for int() with base 10: 'OP_CHECKSIG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/counterparty-cli/counterpartycli/server.py", line 164, in main
    server.start_all(db)
  File "/counterparty-lib/counterpartylib/server.py", line 466, in start_all
    blocks.follow(db)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1240, in follow
    tx_index = list_tx(db, block_hash, block_index, block_time, tx_hash, tx_index, tx_hex)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 934, in list_tx
    source, destination, btc_amount, fee, data = get_tx_info(tx_hex)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 453, in get_tx_info
    return _get_tx_info(tx_hex, block_parser, block_index)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 463, in _get_tx_info
    return  get_tx_info3(tx_hex, block_parser=block_parser)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 586, in get_tx_info3
    return get_tx_info2(tx_hex, block_parser=block_parser, p2sh_support=True)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 681, in get_tx_info2
    new_destination, new_data = decode_checkmultisig(asm)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 650, in decode_checkmultisig
    destination, data = script.construct_array(signatures_required, pubkeyhashes, len(pubkeyhashes)), None
  File "/counterparty-lib/counterpartylib/lib/script.py", line 217, in construct_array
    test_array(signatures_required, pubs, signatures_possible)
  File "/counterparty-lib/counterpartylib/lib/script.py", line 204, in test_array
    raise MultiSigAddressError('Signature values not integers.')
counterpartylib.lib.script.MultiSigAddressError: Signature values not integers.
```

**Comment by longhoangwkm** [comment]
cc @chiguireitor 🙇

**Comment by chiguireitor** [comment]
Fix merged in
