### ISSUE TITLE
[ERROR] Unhandled Exception

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/counterparty-lib#1063]
counterparty-lib branch: master. My node always restart when got this error 

```
[2019-11-27 21:13:42][INFO] Dispenser: 1FwkKA9cqpNRFTpVaokdRjT9Xamvebrwcu opened a dispenser for asset XCP with 10000000000 balance, giving 100000000 XCP for each 75000 BTC[0m
Nov 28, 2019 @ 04:13:43.468
[31m[2019-11-27 21:13:43][ERROR] Unhandled Exception[0m
Nov 28, 2019 @ 04:13:43.468
Traceback (most recent call last):
Nov 28, 2019 @ 04:13:43.468
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1265, in follow
Nov 28, 2019 @ 04:13:43.468
    check.database_version(db)
Nov 28, 2019 @ 04:13:43.468
  File "/counterparty-lib/counterpartylib/lib/check.py", line 231, in database_version
Nov 28, 2019 @ 04:13:43.468
    raise DatabaseVersionError('Client minor version number mismatch ({} ≠ {}).'.format(version_minor, config.VERSION_MINOR), None)
Nov 28, 2019 @ 04:13:43.468
counterpartylib.lib.check.DatabaseVersionError: Client minor version number mismatch (56 ≠ 57).
Nov 28, 2019 @ 04:13:43.468
Nov 28, 2019 @ 04:13:43.468
During handling of the above exception, another exception occurred:
Nov 28, 2019 @ 04:13:43.468
Nov 28, 2019 @ 04:13:43.468
Traceback (most recent call last):
Nov 28, 2019 @ 04:13:43.468
  File "/usr/local/bin/counterparty-server", line 9, in <module>
Nov 28, 2019 @ 04:13:43.468
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
Nov 28, 2019 @ 04:13:43.468
  File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
Nov 28, 2019 @ 04:13:43.468
    server.main()
Nov 28, 2019 @ 04:13:43.468
  File "/counterparty-cli/counterpartycli/server.py", line 164, in main
Nov 28, 2019 @ 04:13:43.468
    server.start_all(db)
Nov 28, 2019 @ 04:13:43.468
  File "/counterparty-lib/counterpartylib/server.py", line 491, in start_all
Nov 28, 2019 @ 04:13:43.468
    blocks.follow(db)
Nov 28, 2019 @ 04:13:43.468
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1270, in follow
Nov 28, 2019 @ 04:13:43.468
    reparse(db, block_index=e.reparse_block_index, quiet=False)
Nov 28, 2019 @ 04:13:43.468
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1020, in reparse
Nov 28, 2019 @ 04:13:43.468
    previous_messages_hash=previous_messages_hash)
Nov 28, 2019 @ 04:13:43.468
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 212, in parse_block
Nov 28, 2019 @ 04:13:43.468
    new_ledger_hash, found_ledger_hash = check.consensus_hash(db, 'ledger_hash', previous_ledger_hash, util.BLOCK_LEDGER)
Nov 28, 2019 @ 04:13:43.468
  File "/counterparty-lib/counterpartylib/lib/check.py", line 131, in consensus_hash
Nov 28, 2019 @ 04:13:43.468
    field, block_index, calculated_hash, found_hash))
Nov 28, 2019 @ 04:13:43.468
counterpartylib.lib.check.ConsensusError: Inconsistent ledger_hash for block 600773 (calculated d635015932dd813b4bf409212f283fd4e7e57399cc68c802028da533c6974966, vs 3b0fc66b8add407bbeab65799a75e41bb86f66ad9
```

**Comment by jdogresorg** [comment]
Seems like your system doesn't have the hotfix which was added to github a few weeks ago.

Try running the following commands
```
cd federatednode/
fednode stop
sudo rm -rf data/counterparty/counterparty.*
cd src/counterparty-lib/
git pull
fednode rebuild counterparty counterparty-testnet
fednode stop
fednode start
```

**Comment by longhoangwkm** [comment]
thanks @jdogresorg, we are using newest version, i checked. error still happened. But after we remove all data and sync from scratch. Error has gone
