### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/counterparty-lib#1064]
- Counterparty-lib: latest https://github.com/CounterpartyXCP/counterparty-lib (1e3380c)
- Testnet

- Error:

```
[2019-12-25 07:06:29][INFO] Block: 1635093 (0.32s, hashes: L:535a2 / TX:33a58 / M:7a86a)
[2019-12-25 07:06:29][INFO] Block: 1635094 (0.27s, hashes: L:5129f / TX:afa3b / M:2bcb0)
[2019-12-25 07:06:29][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 464, in get_tx_info
    return _get_tx_info(tx_hex, block_parser, block_index)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 550, in _get_tx_info
    return  get_tx_info3(tx_hex, block_parser=block_parser)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 673, in get_tx_info3
    return get_tx_info2(tx_hex, block_parser=block_parser, p2sh_support=True)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 833, in get_tx_info2
    raise BTCOnlyError('no data and not unspendable', ctx)
counterpartylib.lib.exceptions.BTCOnlyError: no data and not unspendable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/counterparty-cli/counterpartycli/server.py", line 166, in main
    server.start_all(db)
  File "/counterparty-lib/counterpartylib/server.py", line 491, in start_all
    blocks.follow(db)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1378, in follow
    tx_index = list_tx(db, block_hash, block_index, block_time, tx_hash, tx_index, tx_hex)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1061, in list_tx
    source, destination, btc_amount, fee, data, decoded_tx = get_tx_info(tx_hex)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 471, in get_tx_info
    return b'', None, None, None, None, _get_swap_tx(e.decodedTx, block_parser, block_index)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 532, in _get_swap_tx
    new_source, new_data = decode_p2w(asm)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 734, in decode_p2w
    bech32 = bitcoinlib.bech32.CBech32Data.from_bytes(0, asm[1])
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/bech32.py", line 57, in from_bytes
    self = bytes.__new__(cls, witprog)
TypeError: string argument without an encoding
```

Could you help me check @chiguireitor :bow:

**Comment by longhoangwkm** [comment]
I fixed via https://github.com/longhoangwkm/counterparty-lib/pull/1

**Comment by chiguireitor** [comment]
Worked nicely! Next time plz, open a Pull Request ;)
