### ISSUE TITLE
ParseTransactionError - ConstraintError: UNIQUE constraint failed: issuances.tx_index

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/counterparty-lib#1078]
```
[2020-09-10 00:55:45][WARNING] ParseTransactionError for tx 95d36699e94e53ece011c2fc16735069ff521ad9a77e4de6fb6daa3abfd22d9e: ConstraintError: UNIQUE constraint failed: issuances.tx_index
[2020-09-10 00:55:45][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 126, in parse_tx
    sweep.parse(db, tx, message)
  File "/counterparty-lib/counterpartylib/lib/messages/sweep.py", line 198, in parse
    cursor.execute(sql, bindings)
  File "src/cursor.c", line 236, in resetcursor
apsw.ConstraintError: ConstraintError: UNIQUE constraint failed: issuances.tx_index
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/counterparty-cli/counterpartycli/server.py", line 164, in main
    server.start_all(db)
  File "/counterparty-lib/counterpartylib/server.py", line 491, in start_all
    blocks.follow(db)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1381, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 207, in parse_block
    raise e
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 201, in parse_block
    parse_tx(db, tx)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 147, in parse_tx
    raise exceptions.ParseTransactionError("%s" % e)
counterpartylib.lib.exceptions.ParseTransactionError: ConstraintError: UNIQUE constraint failed: issuances.tx_index
```

**Comment by longhoangwkm** [comment]
Does Counterparty support issuing multiple tokens in 1 transaction ?! @chiguireitor

**Comment by longhoangwkm** [comment]
OH, look like you hotfix here: https://github.com/CounterpartyXCP/counterparty-lib/commit/2a018277cf1f53d1f37785aadc5dfe33a6dffe5d
