### ISSUE TITLE
Mainnet is down for two weeks.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [CounterpartyXCP/counterparty-lib#1090]
Logs on my node.

```
counterparty_1          | [2020-11-13 13:55:38][ERROR] Unhandled Exception
counterparty_1          | Traceback (most recent call last):
counterparty_1          |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1284, in follow
counterparty_1          |     check.database_version(db)
counterparty_1          |   File "/counterparty-lib/counterpartylib/lib/check.py", line 230, in database_version
counterparty_1          |     raise DatabaseVersionError('Client minor version number mismatch ({} ≠ {}).'.format(version_minor, config.VERSION_MINOR), None)
counterparty_1          | counterpartylib.lib.check.DatabaseVersionError: Client minor version number mismatch (58 ≠ 59).
counterparty_1          | 
counterparty_1          | During handling of the above exception, another exception occurred:
counterparty_1          | 
counterparty_1          | Traceback (most recent call last):
counterparty_1          |   File "/usr/local/bin/counterparty-server", line 9, in <module>
counterparty_1          |     load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
counterparty_1          |   File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
counterparty_1          |     server.main()
counterparty_1          |   File "/counterparty-cli/counterpartycli/server.py", line 166, in main
counterparty_1          |     server.start_all(db)
counterparty_1          |   File "/counterparty-lib/counterpartylib/server.py", line 492, in start_all
counterparty_1          |     blocks.follow(db)
counterparty_1          |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1289, in follow
counterparty_1          |     reparse(db, block_index=e.reparse_block_index, quiet=False)
counterparty_1          |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1040, in reparse
counterparty_1          |     previous_messages_hash=previous_messages_hash)
counterparty_1          |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 214, in parse_block
counterparty_1          |     new_ledger_hash, found_ledger_hash = check.consensus_hash(db, 'ledger_hash', previous_ledger_hash, util.BLOCK_LEDGER)
counterparty_1          |   File "/counterparty-lib/counterpartylib/lib/check.py", line 131, in consensus_hash
counterparty_1          |     field, block_index, calculated_hash, found_hash))
counterparty_1          | counterpartylib.lib.check.ConsensusError: Inconsistent ledger_hash for block 618232 (calculated 3e2d6980398e7d1b23be2126046430a78dcb331a4a2597ba1aff04e199522408, vs f478e7eedb6e934dfcd635065aa63724c8eca82995911f6e714c49300a5a5bc5 in database).
```

**Comment by cryptcoin-junkey** [comment]
I found some new commits to the master branch. I'm making the chain re-parse with the HEAD of master.

**Comment by chiguireitor** [comment]
Yup, bootstrap being parsed atm, we found out a non-critical ledger hash inconsistence and are in the processs of parsing the whole blockchain, on block ~624k as of this writing, we made a new change that makes parsing a lot faster, not recommended to reparse as it's a weeklong ordeal.

**Comment by chiguireitor** [comment]
Around 3 secs to parse each block, means reparse will take you around 3 weeks, we're almost done parsing the bootstrap which will make your node boot up very quickly.

**Comment by cryptcoin-junkey** [comment]
It looks the counterparty-server works well with the HEAD of master branch.

```
counterparty_1          | [2020-11-13 21:35:47][INFO] Connecting to database (SQLite 3.24.0-r1).
counterparty_1          | [2020-11-13 21:41:20][INFO] Connecting to backend.
counterparty_1          | [2020-11-13 21:41:20][INFO] Starting API Server.
counterparty_1          | [2020-11-13 21:41:28][INFO] Resuming parsing.
counterparty_1          | [2020-11-13 21:43:44][INFO] Block: 653704 (135.54s, hashes: L:a3be8 / TX:74684 / M:4b21b)
counterparty_1          | [2020-11-13 21:45:24][INFO] Block: 653705 (100.28s, hashes: L:4a632 / TX:5c190 / M:299d9)
counterparty_1          | [2020-11-13 21:47:27][INFO] Block: 653706 (123.14s, hashes: L:826a1 / TX:e4b82 / M:b587d)
counterparty_1          | [2020-11-13 21:48:52][INFO] Send: 2000.0 XCP from 12cBdGC5eysSfnjuncq1MUcXKFFziiFjAp to 33fGgTAWFrKpssKSrpEk4oxnTRUoYqVFj6 (4a9ec67b658a12af43977c1d8c6d99692f47d1c062d1535d0edc13c6d1f4d1a9) [valid]
counterparty_1          | [2020-11-13 21:48:52][INFO] Block: 653707 (85.42s, hashes: L:568a0 / TX:7bbfb / M:96a59)
```

**Comment by chiguireitor** [comment]
Yes, but you won't have correct ledger hashes until you reparse or update from the new bootstrap we will prepare this weekend

**Comment by cryptcoin-junkey** [comment]
I see. It's good to hear the issue is going to be fixed.
I keep this issue open for now.
I'll close this after the new bootstrap available.

**Comment by cryptcoin-junkey** [comment]
I checked services just now.
xchain.io is back. wallet.counterwallet.io is still in trouble with `No counterparty servers are currently available. Please try again later. ERROR: %s`

And I checked fednode on my environment. Log is like following. It looks booting fine.

I close this issue as resolved.

```
counterparty_1          | [2020-11-18 00:02:38][INFO] Running v1.1.5 of counterparty-server.
counterparty_1          | [2020-11-18 00:02:38][INFO] Running v9.59.0 of counterparty-lib.
counterparty_1          | [2020-11-18 00:02:38][INFO] Acquiring lock.
counterparty_1          | [2020-11-18 00:02:38][INFO] Connecting to database (SQLite 3.24.0-r1).
counterparty_1          | [2020-11-18 00:05:15][INFO] Connecting to backend.
counterparty_1          | [2020-11-18 00:05:15][INFO] Starting API Server.
counterparty_1          | [2020-11-18 00:05:19][INFO] Resuming parsing.
counterparty_1          | [2020-11-18 00:08:19][INFO] Expired order: 632c298d108656983ae8ebec56d8dbf2bab7785c47f99e7885f3e2a94b6ff9c5
counterparty_1          | [2020-11-18 00:08:19][INFO] Expired order: 4ffbf7c5d6651dbcdf31af10560a199cc6cd26ddeaf21b42a1c7a0a766867aa1
counterparty_1          | [2020-11-18 00:08:19][INFO] Order: 1CNjUMe6zFAmQaiy5VmYsPRaAL57T4LhGW ordered 0.00770534 A13401453567681343017 for 7 VACUS in 10 blocks, with a provided fee of 0.00019611 BTC and a required fee of 0.00000000 BTC (c9b54d8506bcbd2c832b7484aa1f700feb74ee5ad9b5e499d377ef86cc925dae) [open]
counterparty_1          | [2020-11-18 00:08:19][INFO] Order Match: 7201 VACUS for 0.00770507 A13401453567681343017 (54199f3287c0d84ab8a8c4060270a634aa2c0a1546ae88a80cba55021916aec9_c9b54d8506bcbd2c832b7484aa1f700feb74ee5ad9b5e499d377ef86cc925dae) [completed]
counterparty_1          | [2020-11-18 00:08:19][INFO] Block: 657361 (180.06s, hashes: L:f66c0 / TX:bcf9e / M:e299c)
counterparty_1          | [2020-11-18 00:11:05][INFO] Block: 657362 (166.07s, hashes: L:43059 / TX:3812d / M:799f3)
```

**Comment by cryptcoin-junkey** [comment]
It looks this issue can be avoided by #1097 .
