### ISSUE TITLE
NameError: name 'address' is not defined

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/counterparty-lib#1099]
- Latest version
- Testnet

```
[2021-01-06 01:56:02][WARNING] ParseTransactionError for tx be2185fe8e7fd3f9d7c7273e0c59fd0e83db03cb6ddd3c83af75a29aef619132: name 'address' is not defined
[2021-01-06 01:56:02][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 128, in parse_tx
    dispenser.parse(db, tx, message)
  File "/counterparty-lib/counterpartylib/lib/messages/dispenser.py", line 142, in parse
    action_address = address.unpack(message[LENGTH:LENGTH+21])
NameError: name 'address' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/counterparty-cli/counterpartycli/server.py", line 164, in main
    server.start_all(db)
  File "/counterparty-lib/counterpartylib/server.py", line 491, in start_all
    blocks.follow(db)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1405, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 207, in parse_block
    raise e
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 201, in parse_block
    parse_tx(db, tx)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 147, in parse_tx
    raise exceptions.ParseTransactionError("%s" % e)
counterpartylib.lib.exceptions.ParseTransactionError: name 'address' is not defined
```
cc @chiguireitor

**Comment by chiguireitor** [comment]
Is this using master?

**Comment by chiguireitor** [comment]
Sec, checking rn

**Comment by longhoangwkm** [comment]
https://github.com/CounterpartyXCP/counterparty-lib/commit/5f6ed52f8618a2481055f8a354ba0b66bf94334b

**Comment by chiguireitor** [comment]
Yes, it should be solved on latest master

**Comment by longhoangwkm** [comment]
Thanks, I will pull and rebuild

**Comment by longhoangwkm** [comment]
Ops @chiguireitor I still got that error. It seem can't get `address` module hmm

**Comment by chiguireitor** [comment]
"address.py" should be in your counterpartylib/lib/ directory, please check if you have the latest repo on your libraries dir

**Comment by longhoangwkm** [comment]
Ops, It seems cloud build cached problem. I removed and rebuild the trigger ok now. Thanks, @chiguireitor
