### ISSUE TITLE
MPMA bug: Error composing send transaction via API: string indices must be integers

### ISSUE THREAD

**Issue by longhoangwkm** [CounterpartyXCP/counterparty-lib#1100]
When I create mpma txn with over 2 outputs. I got this error:

```ruby
source: 'mi6fCpyaPBN39ixyYbXdjEMqPntV89RMJc',
destination: ["mypcUU2fYyJav7XUpPLtMVhuPupArLJtiM", "mqx4WiVrGoc3HVg1pDEz6VbjvT9UJqpXtM", "mzQvNPAQQbZDBzhe3SaqncGpATzuqhcUDQ", "mrSdMHTurgPZyE8PtBtmRGmsuzDTU83DGs"],
asset: ["A16706933873489120704", "A16706933873489120704", "A16706933873489120704", "A16706933873489120704"],
quantity: [1999790, 4999790, 9999790, 9999790],
fee: 840)
```

```
({"code"=>-32001, "message"=>"Error composing send transaction via API: string indices must be integers"})


[2021-01-06 09:02:56][WARNING] Error composing send transaction via API: string indices must be integers
[2021-01-06 09:02:56][WARNING] Traceback (most recent call last):
  File "/counterparty-lib/counterpartylib/lib/api.py", line 540, in create_method
    return compose_transaction(self.db, name=tx, params=transaction_args, **common_args)
  File "/counterparty-lib/counterpartylib/lib/api.py", line 405, in compose_transaction
    segwit=segwit)
  File "/counterparty-lib/counterpartylib/lib/transaction.py", line 427, in construct
    dust_return_pubkey = get_dust_return_pubkey(source, provided_pubkeys, encoding)
  File "/counterparty-lib/counterpartylib/lib/transaction.py", line 123, in get_dust_return_pubkey
    dust_return_pubkey_hex = backend.pubkeyhash_to_pubkey(source, provided_pubkeys)
  File "/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 221, in pubkeyhash_to_pubkey
    for vin in tx['vin']:
TypeError: string indices must be integers
```

But If I remove any two elements in an array. The error has gone.
```
(source: 'mi6fCpyaPBN39ixyYbXdjEMqPntV89RMJc',
destination: ["mqx4WiVrGoc3HVg1pDEz6VbjvT9UJqpXtM", "mrSdMHTurgPZyE8PtBtmRGmsuzDTU83DGs"],
asset: ["A16706933873489120704", "A16706933873489120704"],
quantity: [1999790, 499979],
fee: 840)
```
```
0100000001e4ac9a366427e3de0da55d681e1dbd1fdcc662675fc7bd7f2e348e2f972b2420040000001976a9141c5020cf9c04fdd8229dcced2e8e026b62b83f1d88acffffffff020000000000000000516a4c4e112225494fa6792413840933116a9c5067aa6de758ffd4a154323b2ff4469c2d73c163abb28298ff1be54c5a423f627ed64388536cb5273bea688ec5c07ed0b83dc61c8fcfaff38f9a8de378d40e18f39e00000000001976a9141c5020cf9c04fdd8229dcced2e8e026b62b83f1d88ac00000000
```

**Comment by longhoangwkm** [comment]
cc @chiguireitor

**Comment by longhoangwkm** [comment]
`raw_transactions` is a hash map and `tx_id` as key. https://github.com/wakumo/counterparty-lib/commit/09fb4aa73b0176e6b6457bf29b532b0d9dcd522a
I'll make a PR soon

**Comment by chiguireitor** [comment]
That's because if you send an MPMA send for 2 addresses + 2 assets it fits in OP_RETURN, but more than that and you have to do the P2SH encoding, which involves 2 transactions
