### ISSUE TITLE
Error composing send trx: Insufficient BTC at address in Version 9.60.2 - Problem with Addrindexrs get_unspent_txouts

### ISSUE THREAD

**Issue by moonblink** [CounterpartyXCP/counterparty-lib#1242]
The issue with Error composing send transaction via API: Insufficient BTC at address persists.  

Tested using the `create_send` but it is evident in the `create_issuance` as well 

address `bc1qp2mg7dlq6zc92cp6lmausxnhezx0k4fa7cqklv` - this address is not currently in use and is solely for debugging.  The current confirmed utxo's are all sufficient for the fees. However the UTXO's never make it to the the `filtered_unspent` var in `transactions.py` when returned from `backend.get_unspent_txouts`

UTXO's in address
```
UTXO 67fd7dd5ed66b9aba531d4338fa4e59dc189322115852f7ec81824b37ddef5ed:1 is not associated with any transaction in the mempool. Its value is 0.02061550 BTC.
UTXO 67fd7dd5ed66b9aba531d4338fa4e59dc189322115852f7ec81824b37ddef5ed:1 has 105 confirmations.
UTXO ba3d00cdc92181757ecf29fff98ceb9c0012f13bb3f5e47663edd0410e476bb8:0 is not associated with any transaction in the mempool. Its value is 0.11411000 BTC.
UTXO ba3d00cdc92181757ecf29fff98ceb9c0012f13bb3f5e47663edd0410e476bb8:0 has 77 confirmations.
UTXO 1f1c2936a42b822a44f0a96dd89e5c15f205c8509539b9c4d50134649df0068b:0 is not associated with any transaction in the mempool. Its value is 0.03411000 BTC.
UTXO 1f1c2936a42b822a44f0a96dd89e5c15f205c8509539b9c4d50134649df0068b:0 has 101 confirmations.
UTXO 792f6fa4bd2bd9ebc91059ca2bd75ecb93a2629809b32d1b695dfe1f437190dc:0 is not associated with any transaction in the mempool. Its value is 0.03411000 BTC.
UTXO 792f6fa4bd2bd9ebc91059ca2bd75ecb93a2629809b32d1b695dfe1f437190dc:0 has 101 confirmations.
```

Using the below with both unspent_tx param and without produce the same results:
```
        "params": {
            "source": source_address,
            "asset": asset_name,
            "destination": transfer_address,
            "quantity": quantity,
            "unspent_tx_hash": "67fd7dd5ed66b9aba531d4338fa4e59dc189322115852f7ec81824b37ddef5ed"
 ```
 

 when entering line 143 in `transactions.py` the value of `unspent_tx_hash` is defined properly as shown above. 
 ```
 debug output:
[2023-05-21 16:25:53] unspent_tx_hash: 67fd7dd5ed66b9aba531d4338fa4e59dc189322115852f7ec81824b37ddef5ed bc1qp2mg7dlq6zc92cp6lmausxnhezx0k4fa7cqklv
```
 `transactions.py`
 ```
         if unspent_tx_hash is not None:
            unspent = backend.get_unspent_txouts(source, unconfirmed=allow_unconfirmed_inputs, unspent_tx_hash=unspent_tx_hash)
        else:
            unspent = backend.get_unspent_txouts(source, unconfirmed=allow_unconfirmed_inputs)
```

after exiting this code block the `unspent` var is set to `[]`
```
[2023-05-21 16:25:54] Using unspent after check: []
```

This appears to be a problem in the get_unspent_txouts function in `addrindexers.py` returning '[]' whether or not unspent_tx_hash was defined. 

```
def get_unspent_txouts(source):
    ensure_addrindexrs_connected()

    block_count = getblockcount()
    result = _backend.send({
        "method": "blockchain.scripthash.get_utxos",
        "params": [_address_to_hash(source)]
    })

    if not(result is None) and "result" in result:
        result = result["result"]
        result = [unpack_outpoint(x) for x in result]
        # each item on the result array is like
        # {"tx_hash": hex_encoded_hash}
        batch = getrawtransaction_batch([x[0] for x in result], verbose=True, skip_missing=True)
        batch = [unpack_vout(outpoint, batch[outpoint[0]], block_count) for outpoint in result if outpoint[0] in batch]
        batch = [x for x in batch if x is not None]

        return batch
    else:
        return []
   ```
   
 I haven't had time yet to debug the addrindexrs call. Will provide more details as I can. I'm wondering why the call is going to`addrindexrs` instead of directly to bitcoin-core, but I also cannot find much for documentation on `addrindexrs`

**Comment by moonblink** [comment]
This error is also recurring from the `addrindexrs.py`
```
counterparty_1              | [2023-05-21 17:12:44][ERROR] API Exception: {'type': 'AttributeError', 'args': ("'dict' object has no attribute 'split'",), 'message': "'dict' object has no attribute 'split'"}
counterparty_1              | Traceback (most recent call last):
counterparty_1              |   File "/usr/local/lib/python3.6/dist-packages/jsonrpc/manager.py", line 108, in _get_responses
counterparty_1              |     result = method(*request.args, **request.kwargs)
counterparty_1              |   File "/counterparty-lib/counterpartylib/lib/api.py", line 585, in create_method
counterparty_1              |     return compose_transaction(self.db, name=tx, params=transaction_args, **common_args)
counterparty_1              |   File "/counterparty-lib/counterpartylib/lib/api.py", line 450, in compose_transaction 
counterparty_1              |     segwit=segwit)
counterparty_1              |   File "/counterparty-lib/counterpartylib/lib/transaction.py", line 509, in construct
counterparty_1              |     regular_dust_size, disable_utxo_locks
counterparty_1              |   File "/counterparty-lib/counterpartylib/lib/transaction.py", line 150, in construct_coin_selection
counterparty_1              |     unspent = backend.get_unspent_txouts(source, unconfirmed=allow_unconfirmed_inputs)
counterparty_1              |   File "/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 184, in get_unspent_txouts
counterparty_1              |     unspent = BACKEND().get_unspent_txouts(source)
counterparty_1              |   File "/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 442, in get_unspent_txouts
counterparty_1              |     result = [unpack_outpoint(x) for x in result]
counterparty_1              |   File "/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 442, in <listcomp>
counterparty_1              |     result = [unpack_outpoint(x) for x in result]
counterparty_1              |   File "/counterparty-lib/counterpartylib/lib/backend/addrindexrs.py", line 401, in unpack_outpoint
counterparty_1              |     txid, vout = outpoint.split(':')
counterparty_1              | AttributeError: 'dict' object has no attribute 'split'

```

from line 434 in `addrindexrs.py`
```
       result = [unpack_outpoint(x) for x in result]
```

line 400 in `addrindexrs.py`
```
def unpack_outpoint(outpoint):
    txid, vout = outpoint.split(':')
    return (txid, int(vout))
```

**Comment by moonblink** [comment]
Confirmed connection to addrindexrs from the addrindexrs.py

Issue is within this code block:

```
    result = _backend.send({
        "method": "blockchain.scripthash.get_utxos",
        "params": [_address_to_hash(source)]
    })
    ```

**Comment by moonblink** [comment]
Some further validation: 


this is the defined value for the tx_hash being passed from the `create_send`

```
unspent_tx_hash: "67fd7dd5ed66b9aba531d4338fa4e59dc189322115852f7ec81824b37ddef5ed"
```
scriptpubkey as shown in listunspent for above `tx_hash`
```
[
  {
    "txid": "67fd7dd5ed66b9aba531d4338fa4e59dc189322115852f7ec81824b37ddef5ed",
    "vout": 1,
    "address": "1EbjAJUXJYESEAa2dFQR8NZjgsm2hUf3Jk",
    "scriptPubKey": "76a914952af8ba4023c37142d561fc030700d773b0d33288ac",
    "amount": 0.02061550,
    "confirmations": 120,
    "spendable": true,
    "solvable": true,
    "desc": "pkh([16803094/44'/0'/0'/1/1]0292e6a055f9f3ed421d45d412bd06bfed7012f93a0eb4db75892507acee4bfd49)#35hhmyag",
    "parent_descs": [
      "pkh(xpub661MyMwAqRbcFkjJCgrUH2KVALZ2d92t7Hv1o1Hm5aY7Zn7QBq2GYeeNGvZfei5b6K5eeKBF1sYsrgakvU5pb2RgnPsYaypyVZxDC2jw5Ae/44'/0'/0'/1/*)#p2rqqqwz"
    ],
    "safe": true
  },
```

This is the script_hash returned by addrindexrs 

```
2023-05-21 18:08:23]  unspent_tx_hash: 67fd7dd5ed66b9aba531d4338fa4e59dc189322115852f7ec81824b37ddef5ed - address: bc1qp2mg7dlq6zc92cp6lmausxnhezx0k4fa7cqklv
[2023-05-21 18:08:23] Getting UTXOs for address: bc1qp2mg7dlq6zc92cp6lmausxnhezx0k4fa7cqklv
[2023-05-21 18:08:23] Connected to addrindexrs
Script Hash: 2a8b8fdb59eb4afef08a5c07da8ed84c410877be24bdf5e32344ee7161ff1f4f


```
which gets passed to this 
```
    result = _backend.send({
        "method": "blockchain.scripthash.get_utxos",
        "params": [_address_to_hash(source)]
    })
```
which returns:
```
Received result from backend.send: {'id': 336, 'jsonrpc': '2.0', 'result': []}
```

**Comment by moonblink** [comment]
this is the `blockchain_scripthash_get_utxos` function from `rpc.rs` in `addrindexrs` for further debug

```
    fn blockchain_scripthash_get_utxos(&self, params: &[Value]) -> Result<Value> {
        let script_hash = hash_from_value(params.get(0)).chain_err(|| "bad script_hash")?;
        let status = self.query.status(&script_hash[..])?;

        let mut dict = HashMap::new();
        for item in status.funding().into_iter() {
            dict.insert(item.txid.to_hex() + ":" + &item.vout.to_string(), "");
        }

        for item in status.spending().into_iter() {
            dict.remove( &(item.outpoint.0.to_hex() + ":" + &item.outpoint.1.to_string()) );
        }

        let mut utxos = vec![];
        for (outpoint, _drop) in &dict {
            utxos.push(outpoint)
        }

        Ok(json!(utxos))
    }
```

**Comment by moonblink** [comment]
Also this error when rebuilding addrindexrs

```
    warning: unused return value of `Vec::<T, A>::split_off` that must be used
    --> src/util.rs:173:9
     |
 173 |         self.headers.split_off(new_height); // keep [0..new_height) entries
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[warn(unused_must_use)]` on by default
     = note: use `.truncate()` if you don't need the other half
 
 warning: `addrindexrs` (lib) generated 1 warning
     Finished release [optimized] target(s) in 2m 13s
 
```
is fixed  by just truncating since the rest of the record trying to split was not used anyway
 
 replace this
 `self.headers.split_off(new_height); // keep [0..new_height) entries`
 
with this
`self.headers.truncate(new_height); // keep [0..new_height) entries`
 
 on line 173 in utils.rs. 
 
 I can do a PR once i swap over to using my fork. Just wanted to note if.

**Comment by jdogresorg** [comment]
Curious how we are supposed to diagnose CP/addrindexrs UTXO issues with the address `bc1qp2mg7dlq6zc92cp6lmausxnhezx0k4fa7cqklv` you gave for debugging, if there are no UTXOs for CP to try and create a transaction with? 

![image](https://github.com/CounterpartyXCP/counterparty-lib/assets/376028/6ec439f0-a69d-4ef4-8996-048b8f15c4c4)

In order to debug this issue, we need an address where we can reproduce the issue with an CP API call, which we can not do with an address with no usable UTXOs. Can you please find an address which has this issue, and which has some UTXOs that we can use for debugging? We don't need access to the private key or anything, just need to be able to make CP API requests and reproduce the errors your seeing 👍

**Comment by moonblink** [comment]
good point, it's not called walletindexrs :)  My scripts were looking at the utxo's in the wallet and not on the specific address so I was lead down the wrong path on that particular address. I'm verifying things on a couple other addresses and will close if all looks good. Thanks!  

Hopefully the other fixes above are useful.
