### ISSUE TITLE
Support Multiple Parallel Servers

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1318]
```
[2024-01-14 12:33:11][INFO] Received SIGINT.                                                                                                                                    [18/1863]
[2024-01-14 12:33:11][INFO] Stopping backend.                                                                                                                                              
[2024-01-14 12:33:11][INFO] Shutting down.                                                                                                                                                 
(xcp) adam@anaximander:~$ fg                                                                                                                                                               
-bash: fg: current: no such job                                                                                                                                                            
(xcp) adam@anaximander:~$ counterparty-server --database-file full-reparse.sqlite start                                                                                                    
[2024-01-14 12:33:13][INFO] Running v1.1.5 of counterparty-server.                                                                                                                         
[2024-01-14 12:33:13][INFO] Running v9.61.1 of counterparty-lib.                                                                                                                           
[2024-01-14 12:33:13][INFO] Acquiring lock.                                                                                                                                                
[2024-01-14 12:33:13][INFO] Connecting to database (SQLite 3.24.0-r1).                                                                                                                     
[2024-01-14 12:33:13][INFO] Connecting to backend.                                                                                                                                         
[2024-01-14 12:33:13][INFO] AddrIndexRs connecting...                                                                                                                                      
[2024-01-14 12:33:13][INFO] Connected to AddrIndexRs!                                                                                                                                      
[2024-01-14 12:33:13][INFO] Starting API Server.                                                                                                                                           
 * Serving Flask app 'counterpartylib.lib.api' (lazy loading)                                                                                                                              
 * Environment: production                                                                                                                                                                 
   WARNING: This is a development server. Do not use it in a production deployment.                                                                                                        
   Use a production WSGI server instead.                                                                                                                                                   
 * Debug mode: off                                                                                                                                                                         
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/counterparty_lib-9.61.1-py3.9.egg/counterpartylib/lib/api.py", line 1143, in run
    app.run(host=config.RPC_HOST, port=config.RPC_PORT, threaded=True)
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/werkzeug/serving.py", line 1017, in run_simple
    inner()
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/werkzeug/serving.py", line 957, in inner
    srv = make_server(
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/werkzeug/serving.py", line 789, in make_server
    return ThreadedWSGIServer(
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/werkzeug/serving.py", line 693, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
[2024-01-14 12:33:14][INFO] Resuming parsing.
[2024-01-14 12:33:14][INFO] Order: 1HRt3gdnZxxQWfNNCNUgCRy9kLnHviQ78Q ordered 4.071 BTC for 885.0 XCP in 2000 blocks, with a provided fee of 0.04071000 BTC and a required fee of 0.0000000
0 BTC (7cf12dfaa691886b4cd6281fbf4f5b4b81d04bd4c244881f40acc9a1c77f6ab7) [open]
```

**Comment by adamkrellenstein** [comment]
this is silly. you just change the port in the CLI
