### ISSUE TITLE
Fix Version Checking, which is Disabled

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1324]
Right now the minimum version information is hosted using GitHub pages off of the `gh-pages` branch, rather than the `master` branch... that's not good! If we switch it to `master`, it breaks everything, seemingly because of a discrepancy?Also, the version-checking logic is not very robust:

```
Exception in thread Thread-3:                                                                                                                                                              
Traceback (most recent call last):                                                                                                                                                         
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/threading.py", line 980, in _bootstrap_inner                                                                                          
    self.run()                                                                                                                                                                             
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/counterparty_lib-9.61.1-py3.9.egg/counterpartylib/lib/api.py", line 1143, in run                                        
    app.run(host=config.RPC_HOST, port=config.RPC_PORT, threaded=True)                                                                                                                     
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/flask/app.py", line 920, in run                                                                                         
    run_simple(t.cast(str, host), port, self, **options)                                                                                                                                   
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/werkzeug/serving.py", line 1017, in run_simple                                                                          
    inner()                                                                                                                                                                                
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/werkzeug/serving.py", line 957, in inner                                                                                
    srv = make_server(                                                                                                                                                                     
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/werkzeug/serving.py", line 789, in make_server                                                                          
    return ThreadedWSGIServer(                                                                                                                                                             
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/werkzeug/serving.py", line 693, in __init__                                                                             
    super().__init__(server_address, handler)  # type: ignore                                                                                                                              
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/socketserver.py", line 452, in __init__                                                                                               
    self.server_bind()                                                                                                                                                                     
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/http/server.py", line 137, in server_bind                                                                                             
    socketserver.TCPServer.server_bind(self)                                                                                                                                               
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/socketserver.py", line 466, in server_bind                                                                                            
    self.socket.bind(self.server_address)                                                                                                                                                  
OSError: [Errno 98] Address already in use                                                                                                                                                 
[2024-01-15 16:01:53][WARNING] Unable to check version! Expecting value: line 1 column 1 (char 0)                                                                                          
^C[2024-01-15 16:02:03][INFO] Received SIGINT.                                                                                                                                             
[2024-01-15 16:02:03][INFO] Stopping backend.                                                                                                                                              
[2024-01-15 16:02:03][DEBUG] AddrIndexRs thread closing                                
```

```
{'minimum_version_major': 9, 'minimum_version_minor': 59, 'minimum_version_revision': 6, 'block_index': 753500, 'testnet_block_index': 2288000}
{'mainnet': {'1': {'value': '>QQ??If'}, '753500': {'value': '>QQ???'}}, 'testnet': {'1': {'value': '>QQ??If'}, '2288000': {'value': '>QQ???If'}, '2342000': {'value': '>QQ????If'}, '2343963': {'value': '>QQ???'}}}
[2024-01-15 16:11:21][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/adam/.anaconda3/envs/xcp/bin/counterparty-server", line 33, in <module>
    sys.exit(load_entry_point('counterparty-cli==1.1.5', 'console_scripts', 'counterparty-server')())
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/counterpartycli/server.py", line 167, in main
    server.start_all(db)
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/counterparty_lib-9.61.1-py3.9.egg/counterpartylib/server.py", line 494, in start_all
    blocks.follow(db)
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/counterparty_lib-9.61.1-py3.9.egg/counterpartylib/lib/blocks.py", line 1353, in follow
    check.software_version()
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/counterparty_lib-9.61.1-py3.9.egg/counterpartylib/lib/check.py", line 207, in software_version
    check_change(protocol_change, change_name)
  File "/home/adam/.anaconda3/envs/xcp/lib/python3.9/site-packages/counterparty_lib-9.61.1-py3.9.egg/counterpartylib/lib/check.py", line 172, in check_change
    if config.VERSION_MAJOR < protocol_change['minimum_version_major']:
KeyError: 'minimum_version_major'
(xcp) adam@anaximander:~$ 
```

**Comment by adamkrellenstein** [comment]
The GitHub pages site has been unpublished because the protocol changes JSON is invalid. If the site is published with an invalid file, it kills every node.

**Comment by adamkrellenstein** [comment]
See https://github.com/CounterpartyXCP/counterparty-lib/pull/1367
