### ISSUE TITLE
Can't reparse withtout undolog

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterparty-lib#1337]
To debug test book it's important to be able to reparse transactions from a given block:

```
>>> from counterpartylib import server
>>> from counterpartylib.lib import blocks
>>> db = server.initialise(testnet=True, backend_password="PASS")
>>> blocks.reparse(db, block_index=2421058, quiet=False, no_undolog=True)
[2024-01-17 09:59:22][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tower/counterparty/counterparty-lib/counterpartylib/lib/blocks.py", line 1084, in reparse
    reinitialise(db, block_index)
  File "/home/tower/counterparty/counterparty-lib/counterpartylib/lib/blocks.py", line 966, in reinitialise
    initialise(db)
  File "/home/tower/counterparty/counterparty-lib/counterpartylib/lib/blocks.py", line 392, in initialise
    send.initialise(db)
  File "/home/tower/counterparty/counterparty-lib/counterpartylib/lib/messages/send.py", line 69, in initialise
    cursor.execute('ALTER TABLE new_sends RENAME TO sends')
  File "src/cursor.c", line 169, in resetcursor
apsw.SQLError: SQLError: error in trigger _executions_insert: no such table: main.undolog
```

**Comment by ouziel-slama** [comment]
done here https://github.com/CounterpartyXCP/counterparty-lib/pull/1322
