### ISSUE TITLE
`BusyError: database is locked`

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/counterparty-lib#1342]
**Describe the Problem**
Currently, the counterparty-lib software crashes constantly with "db is locked" errors, at least in my experience. This is hidden by the fednode with the docker container auto-restarting after the crash. This doesn't help in finding the issues and fixing them.

**Steps To Reproduce**
1. Try to run a fednode with [this](https://github.com/CounterpartyXCP/federatednode/blob/ef29465b924f72792e302e2c792906d4d41cff1d/docker-compose.tmpl.yml#L95) line commented out.
2. Then apply some load on it.

**Screenshots and Logfiles**
If the steps to reproduce are followed, and your `counterparty` node stops, `fednode tail counterparty` will show an error like this:

```
federatednode-counterparty-1  | [2024-01-17 18:44:50][INFO] Dispenser: bc1qspqfnd73h5tuzwhx345d9asgf8qhun3qn0carf opened a dispenser for asset A1717171717171717171 with 1 balance, giving 1 A1717171717171717171 for each 0.04000000 BTC
federatednode-counterparty-1  | [2024-01-17 18:44:50][ERROR] Unhandled Exception
federatednode-counterparty-1  | Traceback (most recent call last):
federatednode-counterparty-1  |   File "/usr/local/bin/counterparty-server", line 11, in <module>
federatednode-counterparty-1  |     load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
federatednode-counterparty-1  |   File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
federatednode-counterparty-1  |     server.main()
federatednode-counterparty-1  |   File "/counterparty-cli/counterpartycli/server.py", line 174, in main
federatednode-counterparty-1  |     server.start_all(db)
federatednode-counterparty-1  |   File "/counterparty-lib/counterpartylib/server.py", line 499, in start_all
federatednode-counterparty-1  |     blocks.follow(db)
federatednode-counterparty-1  |   File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1483, in follow
federatednode-counterparty-1  |     new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
federatednode-counterparty-1  | apsw.BusyError: BusyError: database is locked
```

`fednode start counterparty` command will get it going again.

```
federatednode-counterparty-1  | [2024-01-17 19:12:37][INFO] Running v1.1.5 of counterparty-server.
federatednode-counterparty-1  | [2024-01-17 19:12:37][INFO] Running v9.61.1 of counterparty-lib.
federatednode-counterparty-1  | [2024-01-17 19:12:37][INFO] Acquiring lock.
federatednode-counterparty-1  | [2024-01-17 19:12:37][INFO] Connecting to database (SQLite 3.24.0-r1).
federatednode-counterparty-1  | [2024-01-17 19:12:37][INFO] Connecting to backend.
federatednode-counterparty-1  | [2024-01-17 19:12:37][INFO] AddrIndexRs connecting...
federatednode-counterparty-1  | [2024-01-17 19:12:37][INFO] Connected to AddrIndexRs!
federatednode-counterparty-1  | [2024-01-17 19:12:37][INFO] Starting MemMempool.
federatednode-counterparty-1  | [2024-01-17 19:12:37][INFO] Starting API Server.
federatednode-counterparty-1  | [2024-01-17 19:12:45][INFO] Resuming parsing.
federatednode-counterparty-1  | [2024-01-17 19:12:49][INFO] Dispenser: bc1qkxg8ymvu4jvjxzlnrld3pujk7ueehkxz77qzrd closed dispenser for A614381762738873840 (operator marked the dispenser to close it)
```

Until it repeats.

It appears like `counterparty` has great uptime, but in reality this "restarting" is just being done constantly behind the scenes by the fednode, a behavior [added](https://github.com/CounterpartyXCP/federatednode/pull/333) not too long ago.

**Comment by adamkrellenstein** [comment]
yep, this is terrible

**Comment by adamkrellenstein** [comment]
IMO, if a single user is having this issues, it's a serious bug.

**Comment by JavierCervilla** [comment]
Im having the same issue actually and not one time in a day, i added that patch (to restart service when die and is restarting it correctly) but is clear for me that there is an actual underlying issue in the code that is not handling correctly the lock of resources of the db, and is generating a data race issue, so solving this bug wont do any bad to anyone.

**Comment by JavierCervilla** [comment]
logs from my instance:

```
federatednode-counterparty-1  | [2024-01-18 15:13:08][ERROR] API Exception: {'type': 'BusyError', 'args': ('BusyError: database is locked',), 'message': 'BusyError: database is locked'}
federatednode-counterparty-1  | Traceback (most recent call last):
federatednode-counterparty-1  |   File "/usr/local/lib/python3.6/dist-packages/jsonrpc/manager.py", line 108, in _get_responses
federatednode-counterparty-1  |     result = method(*request.args, **request.kwargs)
federatednode-counterparty-1  |   File "/counterparty-lib/counterpartylib/lib/api.py", line 687, in get_method
federatednode-counterparty-1  |     return get_rows(self.db, table=table, **kwargs)
federatednode-counterparty-1  |   File "/counterparty-lib/counterpartylib/lib/api.py", line 287, in get_rows
federatednode-counterparty-1  |     query_result = db_query(db, statement, tuple(bindings))
federatednode-counterparty-1  |   File "/counterparty-lib/counterpartylib/lib/api.py", line 144, in db_query
federatednode-counterparty-1  |     results = list(cursor.execute(statement, bindings))
federatednode-counterparty-1  |   File "src/cursor.c", line 236, in resetcursor
federatednode-counterparty-1  | apsw.BusyError: BusyError: database is locked
```

**Comment by adamkrellenstein** [comment]
I just ran into this when making a simple `get_asset_info` API call while catching up. :/

**Comment by adamkrellenstein** [comment]
Turns out that WAL mode works with RO connections since 2018. Turning that on!

**Comment by adamkrellenstein** [comment]
I encourage people to try to run with this patch: #1371
