### ISSUE TITLE
Unhandled Exception on Testnet

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1361]
```
counterparty-server-1  | [2024-01-27 01:55:14][INFO] Block: 278809 (0.09s, hashes: L:e668d / TX:ccdb9 / M:461b5)
counterparty-server-1  | [2024-01-27 01:55:14][DEBUG] Checking version.
counterparty-server-1  | [2024-01-27 01:55:14][WARNING] Unable to check version! Expecting value: line 1 column 1 (char 0)
counterparty-server-1  | [2024-01-27 01:55:14][DEBUG] Skipping transaction: bf591cd2e017a19174ac617f9605643ceb5dcfd3d11e7ab5fde039b3d9507389
counterparty-server-1  | [2024-01-27 01:55:14][DEBUG] Skipping transaction: b42d6ce8bf2dcb2d27afe6690cb722f55a70f0b105e3430d7d70f291b5debd60
counterparty-server-1  | [2024-01-27 01:55:14][DEBUG] Skipping transaction: 8657b8fe9a46cefdb2c23924c88fda256bfd29229fcae499bfd170fa4911d4fd
[...]
2024-01-26 20:55:14 [2024-01-27 01:55:14][DEBUG] Skipping transaction: 7f661ea25e2ba1b1e58047669cc7e08a44fd05298a10fb3164490d8a12d1382e
2024-01-26 20:55:14 [2024-01-27 01:55:14][DEBUG] Skipping transaction: 964755c5a0b919f7d283ccc3566a1e5e2c3ca9b892255765c772ba5f62ff767a
2024-01-26 20:55:14 [2024-01-27 01:55:14][DEBUG] Skipping transaction: d028975847d49fa94a3eac76e502699fbbef36860d7416ac4bfd7cecfad6a73a
2024-01-26 20:55:14 [2024-01-27 01:55:14][WARNING] ParseTransactionError for tx e9e4656570a26519fb5c73afaf97a20016ee0ac8b42f4dc946e6f40f55bbfab4: local variable 'fee' referenced before assignment
2024-01-26 20:55:14 [2024-01-27 01:55:14][ERROR] Unhandled Exception
2024-01-26 20:55:14 Traceback (most recent call last):
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/lib/python3.6/site-packages/counterparty_lib-9.61.1-py3.6.egg/counterpartylib/lib/blocks.py", line 117, in parse_tx
2024-01-26 20:55:14     dividend.parse(db, tx, message)
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/lib/python3.6/site-packages/counterparty_lib-9.61.1-py3.6.egg/counterpartylib/lib/messages/dividend.py", line 211, in parse
2024-01-26 20:55:14     'fee_paid': fee,
2024-01-26 20:55:14 UnboundLocalError: local variable 'fee' referenced before assignment
2024-01-26 20:55:14 
2024-01-26 20:55:14 During handling of the above exception, another exception occurred:
2024-01-26 20:55:14 
2024-01-26 20:55:14 Traceback (most recent call last):
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/bin/counterparty-server", line 33, in <module>
2024-01-26 20:55:14     sys.exit(load_entry_point('counterparty-cli==1.1.5', 'console_scripts', 'counterparty-server')())
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/lib/python3.6/site-packages/counterpartycli/__init__.py", line 16, in server_main
2024-01-26 20:55:14     server.main()
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/lib/python3.6/site-packages/counterpartycli/server.py", line 172, in main
2024-01-26 20:55:14     server.start_all(db)
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/lib/python3.6/site-packages/counterparty_lib-9.61.1-py3.6.egg/counterpartylib/server.py", line 494, in start_all
2024-01-26 20:55:14     blocks.follow(db)
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/lib/python3.6/site-packages/counterparty_lib-9.61.1-py3.6.egg/counterpartylib/lib/blocks.py", line 1483, in follow
2024-01-26 20:55:14     new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/lib/python3.6/site-packages/counterparty_lib-9.61.1-py3.6.egg/counterpartylib/lib/blocks.py", line 211, in parse_block
2024-01-26 20:55:14     raise e
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/lib/python3.6/site-packages/counterparty_lib-9.61.1-py3.6.egg/counterpartylib/lib/blocks.py", line 205, in parse_block
2024-01-26 20:55:14     parse_tx(db, tx)
2024-01-26 20:55:14   File "/root/miniconda3/envs/xcp/lib/python3.6/site-packages/counterparty_lib-9.61.1-py3.6.egg/counterpartylib/lib/blocks.py", line 148, in parse_tx
2024-01-26 20:55:14     raise exceptions.ParseTransactionError("%s" % e)
2024-01-26 20:55:14 counterpartylib.lib.exceptions.ParseTransactionError: local variable 'fee' referenced before assignment
```

**Comment by adamkrellenstein** [comment]
Fixed already.
