### ISSUE TITLE
`plyvel` Dep

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1421]
```
[2024-02-18 14:31:25][WARNING] Warning:
- `/Users/adam/Library/Application Support/counterparty/counterparty.db` will be moved to `/Users/adam/Library/Application Support/counterparty/counterparty.db.old` and recreated from scratch.
- Ensure `addrindexrs` is running and up to date.
- Ensure that `bitcoind` is stopped.
- The initialization may take a while.
Proceed with the initialization? (y/N) : y
[2024-02-18 14:31:26][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/kickstart/blocks_parser.py", line 13, in open_leveldb
    import plyvel
  File "/opt/homebrew/lib/python3.11/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/plyvel/_plyvel.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: <FAF2B9CD-A61E-3EAE-A155-8F3FF2AF6E36> /opt/homebrew/lib/python3.11/site-packages/plyvel/_plyvel.cpython-311-darwin.so
  Reason: tried: '/opt/homebrew/anaconda3/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/anaconda3/lib/libc++.1.dylib' (no such file), '/opt/homebrew/anaconda3/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/anaconda3/lib/libc++.1.dylib' (no such file), '/opt/homebrew/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libc++.1.dylib' (no such file), '/opt/homebrew/lib/libc++.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/libc++.1.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
             ^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-cli/counterpartycli/__init__.py", line 18, in server_main
    server.main()
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-cli/counterpartycli/server.py", line 172, in main
    server.kickstart(
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/server.py", line 506, in kickstart
    kickstarter.run(bitcoind_dir=bitcoind_dir, force=force, last_hash=last_hash, resume_from=resume_from)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/kickstart/__init__.py", line 88, in run
    chain_parser = ChainstateParser(os.path.join(bitcoind_dir, 'chainstate'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/kickstart/blocks_parser.py", line 205, in __init__
    self.ldb = open_leveldb(leveldb_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/kickstart/blocks_parser.py", line 15, in open_leveldb
    raise Exception("Please install the plyvel package via pip3.")
Exception: Please install the plyvel package via pip3.
adam@tang ~/D/w/C/R/counterparty-lib (develop=) > 
```

**Comment by adamkrellenstein** [comment]
I just needed to reinstall the correct version of leveldb and plyvel on macOS
