### ISSUE TITLE
Pickle Error when Connecting to LevelDB

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1429]
```
[2024-02-19 10:27:05][WARNING] Warning:
- `/Users/adam/Library/Application Support/counterparty/counterparty.db` will be moved to `/Users/adam/Library/Application Support/counterparty/counterparty.db.old` and recreated from scratch.
- Ensure `addrindexrs` is running and up to date.
- Ensure that `bitcoind` is stopped.
- The initialization may take a while.
Proceed with the initialization? (y/N) : y
[2024-02-19 10:27:15][INFO] Last known block hash: None
[2024-02-19 10:27:15][INFO] Acquiring lock.
[2024-02-19 10:27:15][INFO] Connecting to database (SQLite 3.44.2.0).
[2024-02-19 10:27:15][ERROR] SQLITE_LOG: no such table: blocks in "SELECT * FROM blocks WHERE block_index = (SELECT MAX(block_index) from blocks)" (1) SQLITE_ERROR
[2024-02-19 10:28:39][INFO] Blocks indexed in: 83.690s
[2024-02-19 10:28:39][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/opt/homebrew/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
             ^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-cli/counterpartycli/__init__.py", line 18, in server_main
    server.main()
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-cli/counterpartycli/server.py", line 172, in main
    server.kickstart(
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/server.py", line 506, in kickstart
    kickstarter.run(bitcoind_dir=bitcoind_dir, force=force, last_hash=last_hash, resume_from=resume_from)
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/kickstart/__init__.py", line 160, in run
    block_parser = BlockchainParser(bitcoind_dir, memory_db, last_parsed_block)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adam/Documents/work/Counterparty/Repos/counterparty-lib/counterpartylib/lib/kickstart/blocks_parser.py", line 68, in __init__
    self.fetch_process.start()
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'apsw.Connection' object
adam@tang ~/D/w/C/R/counterparty-lib (develop=) > 
```

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-lib/commit/eab738e9c4a4098021c01bcaca342e1de5530bc4
