### ISSUE TITLE
Race Condition when Connecting to AddrIndexRS

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#1453]
```
[2024-02-26 10:04:42][INFO] Connecting to address indexer.
check_addrindexrs:  {}
[2024-02-26 10:04:49][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/adam/.local/bin/counterparty-server", line 8, in <module>
    sys.exit(server_main())
             ^^^^^^^^^^^^^
  File "/home/adam/counterparty-cli/counterpartycli/__init__.py", line 18, in server_main
    server.main()
  File "/home/adam/counterparty-cli/counterpartycli/server.py", line 173, in main
    server.kickstart(
  File "/home/adam/counterparty-lib/counterpartylib/server.py", line 506, in kickstart
    kickstarter.run(
  File "/home/adam/counterparty-lib/counterpartylib/lib/kickstart/__init__.py", line 132, in run
    assert check_addrindexrs != {}
AssertionError
adam@aristotle:~/counterparty-lib$
```

This may have been partly fixed unintentionally? But it looks like this assertion is subverting some retry logic.

**Comment by adamkrellenstein** [comment]
Still having this problem with the latest `develop`.

**Comment by adamkrellenstein** [comment]
Fixed
