### ISSUE TITLE
`BackendRPCError` in v9.51.1

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-lib#767]
This problem was reported to me. The problem goes away immediately upon a downgrade to v9.51.0.
```
[ERROR] Unhandled Exception
Traceback (most recent call last):
 File "/usr/local/bin/counterparty-server", line 9, in <module>
   load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
 File "/usr/local/lib/python3.3/dist-packages/counterpartycli/__init__.py", line 16, in server_main
   server.main()
 File "/usr/local/lib/python3.3/dist-packages/counterpartycli/server.py", line 135, in main
   server.start_all(db)
 File "/usr/local/lib/python3.3/dist-packages/counterpartylib/server.py", line 372, in start_all
   blocks.follow(db)
 File "/usr/local/lib/python3.3/dist-packages/counterpartylib/lib/blocks.py", line 912, in follow
   backend.init_mempool_cache()
 File "/usr/local/lib/python3.3/dist-packages/counterpartylib/lib/backend/__init__.py", line 242, in init_mempool_cache
   BACKEND().getrawtransaction_batch(vin_txhash_list, verbose=True)
 File "/usr/local/lib/python3.3/dist-packages/counterpartylib/lib/backend/addrindex.py", line 184, in getrawtransaction_batch
   batch_responses = rpc_batch(payload)
 File "/usr/local/lib/python3.3/dist-packages/counterpartylib/lib/backend/addrindex.py", line 85, in rpc_batch
   responses += rpc_call(chunk)
 File "/usr/local/lib/python3.3/dist-packages/counterpartylib/lib/backend/addrindex.py", line 45, in rpc_call
   raise BackendRPCError('Cannot communicate with backend at `{}`. (server is set to run on {}, is backend?)'.format(url, network))
counterpartylib.lib.backend.addrindex.BackendRPCError: Cannot communicate with backend at `http://user:pass@localhost:20001`. (server is set to run on mainnet, is backend?)
```

**Comment by ouziel-slama** [comment]
do the url `http://user:pass@localhost:20001` is correct ?
do `bitcoind` is up ? (do `getinfo` in command line return someting ?)

**Comment by adamkrellenstein** [comment]
The configuration is exactly the same with v9.51.0 and v9.51.1.

**Comment by ouziel-slama** [comment]
So the error message says that the backend is down. Worth to check and eventually restart it.

**Comment by adamkrellenstein** [comment]
The user can telnet to the server, and it responds to counterparty-lib v9.51.0 just fine. It sounds to me like there's a bug in `rpc_call()`.

**Comment by ouziel-slama** [comment]
hum.. I can not reproduce, `rpc_call()` works well locally, and in the Counterwallet servers. Seems improbable but maybe the installed `bitcoind` do not support batch RPC calls ?

**Comment by ouziel-slama** [comment]
I think it worth to try with a `--requests-timeout` greater than the default 20s, and also with a `--batch-rpc-size` lower than the default 5000.

**Comment by adamkrellenstein** [comment]
AFAIK, this is no longer a problem.

**Comment by Volekss** [comment]
@adamkrellenstein how did you solve this problem?
