### ISSUE TITLE
Unhandled exception with TX cache

### ISSUE THREAD

**Issue by arhuaco** [CounterpartyXCP/counterparty-lib#781]
```
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/xcp/envs/xcp/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/home/xcp/git/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/home/xcp/git/counterparty-cli/counterpartycli/server.py", line 135, in main
    server.start_all(db)  
  File "/home/xcp/git/counterparty-lib/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/home/xcp/git/counterparty-lib/counterpartylib/lib/blocks.py", line 987, in follow
    raw_transactions = backend.getrawtransaction_batch(txhash_list)
  File "/home/xcp/git/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 53, in getrawtransaction_batch
    return BACKEND().getrawtransaction_batch(txhash_list, verbose=verbose)
  File "/home/xcp/git/counterparty-lib/counterpartylib/lib/backend/addrindex.py", line 203, in getrawtransaction_batch
    result[tx_hash] = RAW_TRANSACTIONS_CACHE[tx_hash]['hex']
KeyError: '7440ff91a9dd7349f0538fa4687dc01338756ce9c7fbfe224dc175fcac670ccd'
```

**Comment by adamkrellenstein** [comment]
@arhuaco: what version are you running?

**Comment by arhuaco** [comment]
[INFO] Running v1.1.1 of counterparty-server.
[INFO] Running v9.51.2 of counterparty-lib.

It seems I need to update. I'll close and reopen if I see this later.
