### ISSUE TITLE
KeyError in raw_transactions_cache

### ISSUE THREAD

**Issue by deweller** [CounterpartyXCP/counterparty-lib#788]
I just experienced this crash in Counterparty Server.

I'm running the latest develop branch (699f5b73e3dcda79ffb9e223f3dde138a64f81ad).

```
2015-08-06-T22:07:58+0000 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/blocks.py", line 1069, in follow
    mempool_tx_index = list_tx(db, None, block_index, curr_time, tx_hash, mempool_tx_index)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/blocks.py", line 712, in list_tx
    backend.extract_addresses(tx_hash) # prepare cache for backend.unconfirmed_transactions().
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/backend/__init__.py", line 63, in extract_addresses
    return BACKEND().extract_addresses(tx_hash)
  File "/usr/lib/python3.4/functools.py", line 452, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/backend/addrindex.py", line 105, in extract_addresses
    raw_transactions = getrawtransaction_batch(txhash_list, verbose=True)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/backend/addrindex.py", line 207, in getrawtransaction_batch
    result[tx_hash] = raw_transactions_cache[tx_hash]
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/util.py", line 633, in __getitem__
    return self.dict[key]
KeyError: 'e951e79d2140b1844d5058bd0f609e3939b040132a1d920ec89c55a2392ef83f'
```

**Comment by ouziel-slama** [comment]
@deweller, this should be resolved with the last commit of @robby-dermody : https://github.com/CounterpartyXCP/counterparty-lib/commit/581b3466528a4be4a0f37853a973df1264a183ed
