### ISSUE TITLE
KeyError issue

### ISSUE THREAD

**Issue by mtbitcoin** [CounterpartyXCP/counterparty-lib#807]
Running bitcoind 0.11.1 and counterpartylib 9.52 on a windows box (issue also confirmed by ebx on arh Linux) I am occasionally encountering the following error. A reindex as suggested by robby was also performed but that did not help

2015-11-07-T08:19:23Coordinated Universal Time [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\counterpartylib\lib\backend\addrindex.py", line 228, in getrawtransaction_batch
    result[tx_hash] = raw_transactions_cache[tx_hash]
  File "c:\python34\lib\site-packages\counterpartylib\lib\util.py", line 639, in **getitem**
    return self.dict[key]
KeyError: 'd0204cc661e5fb3c073e7710c5742b1380a5f1c15a5d32574edbebaebfeec0ec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\counterparty-server-script.py", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "c:\python34\lib\site-packages\counterpartycli__init__.py", line 16, in server_main
    server.main()
  File "c:\python34\lib\site-packages\counterpartycli\server.py", line 135, in main
    server.start_all(db)
  File "c:\python34\lib\site-packages\counterpartylib\server.py", line 372, in start_all
    blocks.follow(db)
  File "c:\python34\lib\site-packages\counterpartylib\lib\blocks.py", line 1207, in follow
    mempool_tx_index = list_tx(db, None, block_index, curr_time, tx_hash, mempool_tx_index)
  File "c:\python34\lib\site-packages\counterpartylib\lib\blocks.py", line 843, in list_tx
    backend.extract_addresses([tx_hash,]) # prepare cache for backend.unconfirmed_transactions().
  File "c:\python34\lib\site-packages\counterpartylib\lib\backend__init__.py", line 66, in extract_addresses
    return BACKEND().extract_addresses(txhash_list)
  File "c:\python34\lib\site-packages\counterpartylib\lib\backend\addrindex.py", line 103, in extract_addresses
    raw_transactions = getrawtransaction_batch(list(tx_inputs_hashes), verbose=True)
  File "c:\python34\lib\site-packages\counterpartylib\lib\backend\addrindex.py", line 236, in getrawtransaction_batch
    r = getrawtransaction_batch([tx_hash], verbose=verbose, _recursing=True)
  File "c:\python34\lib\site-packages\counterpartylib\lib\backend\addrindex.py", line 228, in getrawtransaction_batch
    result[tx_hash] = raw_transactions_cache[tx_hash]
  File "c:\python34\lib\site-packages\counterpartylib\lib\util.py", line 639, in __getitem__
    return self.dict[key]
KeyError: 'd0204cc661e5fb3c073e7710c5742b1380a5f1c15a5d32574edbebaebfeec0ec'
##

**Comment by unsystemizer** [comment]
There's a similar corruption issue with Bitcoin - https://github.com/bitcoin/bitcoin/issues/6528 - and it's interesting that it can persist even after `reindex`. Might not necessarily be related, but it could be.

**Comment by robby-dermody** [comment]
Ultimately due to flakeyness with `addrindex`. Upcoming 9.53.0 release might better address this:

https://github.com/CounterpartyXCP/counterparty-lib/commit/47ba5f246440ea7c6531734687e976aefe067ca7

**Comment by unsystemizer** [comment]
Just ran into this today with 9.52 as well.

I didn't restart so my CP DB is as-is. If you want a copy for post mortem lemme know otherwise I'll start it tomorrow.

Some basic info (the rest is the same as above):

* Crashed at block 387125 or during 387126
* `KeyError: '171988531c67506d390363e7da5b92c2c9c40f248ac71bcaa321ffc225741142'`

**Comment by robby-dermody** [comment]
@unsystemizer what version of bitcoin core

**Comment by unsystemizer** [comment]
0.11.2

**Comment by robby-dermody** [comment]
You can try with the newest `develop` version, which includes several things (by myself and @rubensayshi) which may help

**Comment by unsystemizer** [comment]
Okay, running `develop` now, will report back if I see this again.

**Comment by unsystemizer** [comment]
Ran into this again around block 388328-9.
```
user@system:~$ counterparty-server --version
counterparty-server v1.1.1; counterparty-lib v9.53.0
```
Error:
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/blocks.py", line 1175, in follow
    backend.init_mempool_cache()
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/__init__.py", line 257, in init_mempool_cache
    BACKEND().getrawtransaction_batch(vin_txhash_list[:max_remaining_num_tx], verbose=True)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 302, in getrawtransaction_batch
    r = getrawtransaction_batch([tx_hash], verbose=verbose, _retry=_retry+1)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 302, in getrawtransaction_batch
    r = getrawtransaction_batch([tx_hash], verbose=verbose, _retry=_retry+1)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 294, in getrawtransaction_batch
    result[tx_hash] = raw_transactions_cache[tx_hash]
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/util.py", line 639, in __getitem__
    return self.dict[key]
KeyError: 'b19b6531ce27a60711c43e5ea021980ccd190bdc2f6bf14e68662ffc90ff0765'
```

**Comment by unsystemizer** [comment]
With v9.53.0 and Core 0.11.2, I came across this again. I thought to share this because:
 
*  `skip_missing` was introduced in v.9.53.0 and I thought it may make counterparty-lib behave differently, and 
* I happened to be logged in while this was going on and I noticed that `bitcoin-cli getinfo` couldn't get response from Bitcoin Core for for many minutes. Maybe this problem is related to https://github.com/bitcoin/bitcoin/pull/5677. All the while Bitcoin Core is working fine and is up to date (except for RPC).

Note: the current block height is 397371, my CP server is was catching up, at 390168.

```
2016-02-08-T10:51:15+0000 [INFO] Block: 390168 (24.12s, hashes: L:afbe4 / TX:4c227 / M:f6ff4)
2016-02-08-T10:51:28+0000 [INFO] Block: 390169 (13.11s, hashes: L:56a12 / TX:9abf7 / M:7dbf5)
2016-02-08-T11:11:35+0000 [WARNING] tx missing in rawtx cache: 'a724ab8af5f322e03ea6cf1548c697a3383ed75fa68f7bf0c7c2d2180b60262c' -- txhash_list size: 476, hash: 5a1caaf04f7e673cbc2798ba0021b78b / raw_transactions_cache size: 1583 / # rpc_batch calls: 476 / txhash in noncached_txhashes: True / txhash in txhash_list: True -- list []
2016-02-08-T11:16:35+0000 [WARNING] tx missing in rawtx cache: 'a724ab8af5f322e03ea6cf1548c697a3383ed75fa68f7bf0c7c2d2180b60262c' -- txhash_list size: 1, hash: 9c46332d4466fb0ea534fb66d39acfb7 / raw_transactions_cache size: 1583 / # rpc_batch calls: 1 / txhash in noncached_txhashes: True / txhash in txhash_list: True -- list []
2016-02-08-T11:21:36+0000 [WARNING] tx missing in rawtx cache: 'a724ab8af5f322e03ea6cf1548c697a3383ed75fa68f7bf0c7c2d2180b60262c' -- txhash_list size: 1, hash: 9c46332d4466fb0ea534fb66d39acfb7 / raw_transactions_cache size: 1583 / # rpc_batch calls: 1 / txhash in noncached_txhashes: True / txhash in txhash_list: True -- list []
2016-02-08-T11:21:36+0000 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 300, in getrawtransaction_batch
    result[tx_hash] = raw_transactions_cache[tx_hash]['hex'] if raw_transactions_cache[tx_hash] is not None else None
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/util.py", line 639, in __getitem__
    return self.dict[key]
KeyError: 'a724ab8af5f322e03ea6cf1548c697a3383ed75fa68f7bf0c7c2d2180b60262c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 300, in getrawtransaction_batch
    result[tx_hash] = raw_transactions_cache[tx_hash]['hex'] if raw_transactions_cache[tx_hash] is not None else None
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/util.py", line 639, in __getitem__
    return self.dict[key]
KeyError: 'a724ab8af5f322e03ea6cf1548c697a3383ed75fa68f7bf0c7c2d2180b60262c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/blocks.py", line 1124, in follow
    raw_transactions = backend.getrawtransaction_batch(txhash_list)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/__init__.py", line 58, in getrawtransaction_batch
    return BACKEND().getrawtransaction_batch(txhash_list, verbose=verbose, skip_missing=skip_missing)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 306, in getrawtransaction_batch
    r = getrawtransaction_batch([tx_hash], verbose=verbose, skip_missing=skip_missing, _retry=_retry+1)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 306, in getrawtransaction_batch
    r = getrawtransaction_batch([tx_hash], verbose=verbose, skip_missing=skip_missing, _retry=_retry+1)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 300, in getrawtransaction_batch
    result[tx_hash] = raw_transactions_cache[tx_hash]['hex'] if raw_transactions_cache[tx_hash] is not None else None
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.53.0-py3.4.egg/counterpartylib/lib/util.py", line 639, in __getitem__
    return self.dict[key]
KeyError: 'a724ab8af5f322e03ea6cf1548c697a3383ed75fa68f7bf0c7c2d2180b60262c'
```

**Comment by robby-dermody** [comment]
So on `cw01`, I've seen a few warnings like:
```
2016-02-07-T20:41:14+0000 [WARNING] tx missing in rawtx cache: '26e7b7683bfbfc3fcdd86cf82ca525fc6cec131129ff9da69b2d1e233798b2a7' -- txhash_list size: 2, hash: 77f98b44258d54554449b
6d9ffd16d15 / raw_transactions_cache size: 19999 / # rpc_batch calls: 2 / txhash in noncached_txhashes: True / txhash in txhash_list: True -- list []
```

However, none of them (since November 30th at least) led to a `KeyError`. It seems that the retry logic always works there. However, I'm guessing that on slower/less well-provisioned systems than `cw01`, we might be running into a race condition. Tx malleability could be an issue too (not with counterparty transactions, but with others possibly)...however if that were the case, I'd naively expect the issue to consistently not appear to resolve itself and lead to `KeyErrors`.

@rubensayshi ...any ideas?

**Comment by unsystemizer** [comment]
I straced `bitcoin-cli getinfo` before I shut down Bitcoin Core and invariably it waits when it gets this response from Bitcoin Core RPC (2 hours in this case, before I CTRL+C-ed it:
`ERESTARTSYS (To be restarted if SA_RESTART is set)`
It'd be interesting to know if Bitcoin RPC server always does this when this error appears. The Bitcoin Core issue I linked (#5677) and other similar issues (an easy way to repro can be found here: https://github.com/bitcoin/bitcoin/issues/2889#issuecomment-37683669) mention that the RPC server sometimes recovers, and sometimes not. It may be more frequent on systems with less resources, but it may be indirectly caused by a Bitcoin Core bug.

```
12:17:57 gettimeofday({1454933877, 350523}, NULL) = 0
12:17:57 sendto(6, "\24\0\0\0\26\0\1\3u\207\270V\0\0\0\0\0\0\0\0", 20, 0, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 20
12:17:57 recvmsg(6, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"L\0\0\0\24\0\2\0u\207\270V\t.\0\0\2\10\200\376\1\0\0\0\10\0\1\0\177\0\0\1"..., 4096}], msg_controllen=0, msg_flags=0}, 0) = 164
12:17:57 recvmsg(6, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"\24\0\0\0\3\0\2\0u\207\270V\t.\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 20
12:17:57 close(6)                       = 0
12:17:57 socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 6
12:17:57 epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLET, {u32=1422769200, u64=1422769200}}) = 0
12:17:57 connect(6, {sa_family=AF_INET, sin_port=htons(8332), sin_addr=inet_addr("127.0.0.1")}, 16) = 0
12:17:57 sendmsg(6, {msg_name(0)=NULL, msg_iov(1)=[{"POST / HTTP/1.1\r\nUser-Agent: bit"..., 281}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 281
12:17:57 recvmsg(6, 0x7ee9c028, 0)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
14:12:05 --- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL, si_value={int=1996361548, ptr=0x76fe0f4c}} ---
14:12:05 +++ killed by SIGINT +++
```

**Comment by unsystemizer** [comment]
Still getting this with v9.54.0 and Bitcoin Core 0.12rc1 (from btcdrak).
