### ISSUE TITLE
Type error in  refresh_unconfirmed_transactions_cache()

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#809]
* counterparty-server v1.1.1; counterparty-lib v9.52.0
* btcd 0.11.1 beta

```
INFO] Mempool cache initialized: 0.00s for 0 transactions
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/blocks.py", line 1169, in follow
    backend.refresh_unconfirmed_transactions_cache(old_mempool_hashes)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/backend/__init__.py", line 69, in refresh_unconfirmed_transactions_cache
    return BACKEND().refresh_unconfirmed_transactions_cache(mempool_txhash_list)
TypeError: refresh_unconfirmed_transactions_cache() takes 0 positional arguments but 1 was given
```

**Comment by unsystemizer** [comment]
I see it's not implemented because we're waiting for https://github.com/btcsuite/btcd/issues/329.
Since the same is already mentioned in https://github.com/CounterpartyXCP/counterparty-lib/blob/develop/counterpartylib/lib/backend/btcd.py#L73, I'll close this issue.
