### ISSUE TITLE
[btcd] TypeError: refresh_unconfirmed_transactions_cache()

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterparty-lib#831]
While testing btcd, this happens after re-parsing testnet from bootstrap db on counterpartylib 9.52.0 release version and on latest git develop (last commit: [2015-12-29](https://github.com/CounterpartyXCP/counterparty-lib/commit/5f516ff8968785b5a69f396b4c05585c62c0f1b7)):

```
[INFO] Block (re-parse): 630311 (hashes: L:b3c2f / TX:2ad00 / M:32a03)
[DEBUG] Checking for conservation of assets.
[DEBUG] ZATEST has been conserved (100 ZATEST both issued and held)
(output trimmed)
[DEBUG] A1111111111111111111 has been conserved (100000000.0 A1111111111111111111 both issued and held)
[DEBUG] TTTT has been conserved (1510000.0 TTTT both issued and held)
[DEBUG] MARTEXCOIN has been conserved (5000000.0 MARTEXCOIN both issued and held)
[INFO] Database version number updated.
[INFO] Resuming parsing.
[DEBUG] Initializing mempool cache...
[INFO] Mempool cache initialized: 10.96s for 2,403 transactions
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/lib/python3.5/site-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/lib/python3.5/site-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/lib/python3.5/site-packages/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/lib/python3.5/site-packages/counterpartylib/lib/blocks.py", line 1169, in follow
    backend.refresh_unconfirmed_transactions_cache(old_mempool_hashes)
  File "/usr/lib/python3.5/site-packages/counterpartylib/lib/backend/__init__.py", line 69, in refresh_unconfirmed_transactions_cache
    return BACKEND().refresh_unconfirmed_transactions_cache(mempool_txhash_list)
TypeError: refresh_unconfirmed_transactions_cache() takes 0 positional arguments but 1 was given
```

It reads 630111 blockchain reorganisation after a restart, but throws the same error:

```
[2016-01-03 23:08:23][DEBUG] A1963318209936205000 has been conserved (1000000.0 A1963318209936205000 both issued and held)
[2016-01-03 23:08:23][INFO] Database version number updated.
[2016-01-03 23:08:23][DEBUG] Checking that block 630311 is not an orphan.
[2016-01-03 23:08:23][DEBUG] Checking version.
[2016-01-03 23:08:24][DEBUG] Version check passed.
[2016-01-03 23:08:25][DEBUG] Skipping transaction: 8e7b4d7e2051e33d1572a3ff7c5fcc14cef247095d7d4a913de104376e32b705
(output trimmed)
[2016-01-03 23:08:48][DEBUG] Skipping transaction: 181b421c8aabb413222a960397bc2de9514a4e45208e586c050c4243adf3d813
[2016-01-03 23:08:48][INFO] Block: 630311 (25.14s, hashes: L:b3c2f / TX:2ad00 / M:32a03)
[2016-01-03 23:08:48][DEBUG] Checking that block 630312 is not an orphan.
[2016-01-03 23:08:49][DEBUG] Checking version.
[2016-01-03 23:08:49][DEBUG] Version check passed.
[2016-01-03 23:08:51][DEBUG] Skipping transaction: d7ed12b436959f8bfa8f85e8269822ca53d0ee4a940f05ef556d2d007a4ee079
(output trimmed)
[2016-01-03 23:08:51][DEBUG] Skipping transaction: bc0fc6bc8518d38c219c839e89c1f7fe0579566ef662420928f6262a8a1e2bb3
[2016-01-03 23:08:51][DEBUG] Checking for conservation of assets.
[2016-01-03 23:08:51][DEBUG] COCOCOIN has been conserved (1000000.0 COCOCOIN both issued and held)
(output trimmed)
[2016-01-03 23:08:51][DEBUG] A1963318209936205000 has been conserved (1000000.0 A1963318209936205000 both issued and held)
[2016-01-03 23:08:51][INFO] Block: 630312 (2.31s, hashes: L:025e3 / TX:abdde / M:12a98)
[2016-01-03 23:08:51][DEBUG] Initializing mempool cache...
[2016-01-03 23:09:02][INFO] Mempool cache initialized: 11.19s for 2,558 transactions
[2016-01-03 23:09:02][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/lib/python3.5/site-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/lib/python3.5/site-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/lib/python3.5/site-packages/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/lib/python3.5/site-packages/counterpartylib/lib/blocks.py", line 1176, in follow
    backend.refresh_unconfirmed_transactions_cache(old_mempool_hashes)
  File "/usr/lib/python3.5/site-packages/counterpartylib/lib/backend/__init__.py", line 70, in refresh_unconfirmed_transactions_cache
    return BACKEND().refresh_unconfirmed_transactions_cache(mempool_txhash_list)
TypeError: refresh_unconfirmed_transactions_cache() takes 0 positional arguments but 1 was given
```

**Comment by atweiden** [comment]
Closing, seems [NYI](https://github.com/CounterpartyXCP/counterparty-lib/blob/74a21a60f6ba8b8f5f74532c05a6c6595f486e20/counterpartylib/lib/backend/btcd.py#L101)

**Comment by rubensayshi** [comment]
yea there's a few things not implemented yet for btcd and we're waiting for JSON 2.0 support so we can batch commands
