### ISSUE TITLE
Possibly incorrect hardcoded testnet checkpoints.

### ISSUE THREAD

**Issue by F483** [CounterpartyXCP/counterparty-lib#926]
When running an initial sync on testnet, the hardcoded checkpoints do not match.

The output below is from a fresh setup installed in a virtualenv.

Error:

```
$ counterparty-server --testnet --backend-port=18332 --backend-user=bitcoinrpcuser --backend-password=bitcoinrpcpass start
.
.
.
[2016-08-18 03:18:37][INFO] Block: 649997 (0.14s, hashes: L:ed719 / TX:7decf / M:cafed)
[2016-08-18 03:18:37][INFO] Block: 649998 (0.14s, hashes: L:eba7b / TX:e17c7 / M:c769e)
[2016-08-18 03:18:37][INFO] Block: 649999 (0.14s, hashes: L:8e0c7 / TX:09972 / M:f7d98)
[2016-08-18 03:18:37][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/home/f483/dev/counterparty/counterparty-cli/env/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.2', 'console_scripts', 'counterparty-server')()
  File "/home/f483/dev/counterparty/counterparty-cli/env/lib/python3.4/site-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/home/f483/dev/counterparty/counterparty-cli/env/lib/python3.4/site-packages/counterpartycli/server.py", line 155, in main
    server.start_all(db)
  File "/home/f483/dev/counterparty/counterparty-cli/env/lib/python3.4/site-packages/counterpartylib/server.py", line 408, in start_all
    blocks.follow(db)
  File "/home/f483/dev/counterparty/counterparty-cli/env/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 1171, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = parse_block(db, block_index, block_time)
  File "/home/f483/dev/counterparty/counterparty-cli/env/lib/python3.4/site-packages/counterpartylib/lib/blocks.py", line 190, in parse_block
    new_txlist_hash, found_txlist_hash = check.consensus_hash(db, 'txlist_hash', previous_txlist_hash, txlist)
  File "/home/f483/dev/counterparty/counterparty-cli/env/lib/python3.4/site-packages/counterpartylib/lib/check.py", line 119, in consensus_hash
    raise ConsensusError('Incorrect {} for block {}.'.format(field, block_index))
counterpartylib.lib.check.ConsensusError: Incorrect txlist_hash for block 650000.
```

Installed python packages:

```
$ pip freeze
Warning: cannot find svn location for apsw==3.9.2-r1
Flask==0.11
Flask-HTTPAuth==3.1.2
Jinja2==2.8
MarkupSafe==0.23
Werkzeug==0.11.10
appdirs==1.4.0
## FIXME: could not find svn URL in dependency_links for this package:
apsw==3.9.2-r1
cachetools==1.1.6
click==6.6
colorlog==2.7.0
counterparty-cli==1.1.2
counterparty-lib==9.55.0
coverage==4.2
itsdangerous==0.24
json-rpc==1.10.3
prettytable==0.7.2
py==1.4.31
pycoin==0.62
pycrypto==2.6.1
pysha3==0.3
pytest==2.9.1
pytest-cov==2.2.1
python-bitcoinlib==0.5.1
python-dateutil==2.5.3
requests==2.10.0
six==1.10.0
tendo==0.2.8
xmltodict==0.10.1
```

Python version:

```
$ python --version
Python 3.4.3
```
##

**Comment by unsystemizer** [comment]
@rubensayshi I hit this today while reparsing `counterparty.testnet.db`.

Strangely, the same Bitcoin Core instance worked fine 2 weeks ago (testnet block height at the time was 900K, so above this place where the error occurs).

At that time I used the exact same server with Bitcoin Core (haven't even restarted it) and counterparty-server was running inside of a different Ubuntu 16.04 VM. Now the VM has been reinstalled, but as far as I can tell everything is the same configuration wise. 

I used `-v` to fetch one additional detail, which is the problematic transaction. Don't know if that can help.

```
2016-11-10-T00:08:13-0800 [DEBUG] Version check passed.
2016-11-10-T00:08:13-0800 [DEBUG] Skipping transaction: b6531e22d23fcbb19485f748                                                                                                                                                      8f7304e8ad23f141be50017287de20d9fdc50230
2016-11-10-T00:08:13-0800 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 11, in <module>
    load_entry_point('counterparty-cli==1.1.2', 'console_scripts', 'counterparty                                                                                                                                                      -server')()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/__init__.py", lin                                                                                                                                                      e 16, in server_main
    server.main()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/server.py", line                                                                                                                                                       155, in main
    server.start_all(db)
  File "/home/user/counterparty-lib-master/counterpartylib/server.py", line 408,                                                                                                                                                       in start_all
    blocks.follow(db)
  File "/home/user/counterparty-lib-master/counterpartylib/lib/blocks.py", line                                                                                                                                                       1171, in follow
    new_ledger_hash, new_txlist_hash, new_messages_hash, found_messages_hash = p                                                                                                                                                      arse_block(db, block_index, block_time)
  File "/home/user/counterparty-lib-master/counterpartylib/lib/blocks.py", line                                                                                                                                                       190, in parse_block
    new_txlist_hash, found_txlist_hash = check.consensus_hash(db, 'txlist_hash',                                                                                                                                                       previous_txlist_hash, txlist)
  File "/home/user/counterparty-lib-master/counterpartylib/lib/check.py", line 1                                                                                                                                                      19, in consensus_hash
    raise ConsensusError('Incorrect {} for block {}.'.format(field, block_index)                                                                                                                                                      )
counterpartylib.lib.check.ConsensusError: Incorrect txlist_hash for block 650000                                                                                                                                                      .

```

**Comment by unsystemizer** [comment]
More fun:

```
$ counterparty-server rollback 649990
[2016-11-10 00:15:41][INFO] Running v1.1.2 of counterparty-server.
[2016-11-10 00:15:41][INFO] Running v9.55.0 of counterparty-lib.
[2016-11-10 00:15:41][INFO] Acquiring lock.
[2016-11-10 00:15:41][INFO] Connecting to database.
[2016-11-10 00:15:46][INFO] Connecting to backend.
[2016-11-10 00:15:46][INFO] Rolling back transactions to block 649990.
[2016-11-10 00:15:46][INFO] Database version number updated.
```

Then:

```
[2016-11-10 00:16:23][DEBUG] Version check passed.
[2016-11-10 00:16:23][DEBUG] Skipping transaction: a06c79065853ed817e81fb55a1849b58c0fcce34d747469469cd12857bbdd0ef
[2016-11-10 00:16:23][INFO] Block: 649991 (0.56s, hashes: L:876fb / TX:07d9a / M:f4547)
[2016-11-10 00:16:23][DEBUG] Checking that block 649992 is not an orphan.
[2016-11-10 00:16:23][DEBUG] Checking version.
[2016-11-10 00:16:24][DEBUG] Version check passed.
[2016-11-10 00:16:24][DEBUG] Skipping transaction: bde49db834609589183b6e1d4cf3a4cc3fefe0c15dcd9a775ac18edc4fe7fac7
[2016-11-10 00:16:24][INFO] Block: 649992 (0.49s, hashes: L:48df2 / TX:a25f7 / M:5433a)
[2016-11-10 00:16:24][DEBUG] Checking that block 649993 is not an orphan.
[2016-11-10 00:16:24][DEBUG] Checking version.
[2016-11-10 00:16:24][DEBUG] Version check passed.
[2016-11-10 00:16:24][DEBUG] Skipping transaction: 3b32145b6cbc07158894696037af97908599fa2b8e68922380f74caacbf8e29c
[2016-11-10 00:16:24][INFO] Block: 649993 (0.49s, hashes: L:37db5 / TX:45e59 / M:3c118)
[2016-11-10 00:16:24][DEBUG] Checking that block 649994 is not an orphan.
[2016-11-10 00:16:24][DEBUG] Checking version.
[2016-11-10 00:16:25][DEBUG] Version check passed.
[2016-11-10 00:16:25][DEBUG] Skipping transaction: 80bf352ddf5dd290e918b73ad086af7e05b60753b84d67106444fcc924d17b80
[2016-11-10 00:16:25][INFO] Block: 649994 (0.50s, hashes: L:da1f2 / TX:71406 / M:c34c8)
[2016-11-10 00:16:25][DEBUG] Checking that block 649995 is not an orphan.
[2016-11-10 00:16:25][DEBUG] Checking version.
[2016-11-10 00:16:25][DEBUG] Version check passed.
[2016-11-10 00:16:25][DEBUG] Skipping transaction: b9b5a90dfdcae14a41a33cb13cf78ae841de3a2ef9da840b90b29013b66b063b
[2016-11-10 00:16:25][INFO] Block: 649995 (0.48s, hashes: L:2b99b / TX:22c69 / M:7e9f2)
[2016-11-10 00:16:25][DEBUG] Checking that block 649996 is not an orphan.
[2016-11-10 00:16:25][DEBUG] Checking version.
[2016-11-10 00:16:26][DEBUG] Version check passed.
[2016-11-10 00:16:26][DEBUG] Skipping transaction: df1d1dd0ed68e16c11b780033d49cdab09a8b1b57c61a2a20c01b7187717eeb6
[2016-11-10 00:16:26][DEBUG] Skipping transaction: e6ef4e3bb4d186992b108be0721024e2b24ae8fccca0d2b5c11b2e5e1be4b186
[2016-11-10 00:16:26][INFO] Block: 649996 (0.51s, hashes: L:aad40 / TX:bf857 / M:c36bd)
[2016-11-10 00:16:26][DEBUG] Checking that block 649997 is not an orphan.
[2016-11-10 00:16:26][DEBUG] Checking version.
[2016-11-10 00:16:26][DEBUG] Version check passed.
[2016-11-10 00:16:26][DEBUG] Skipping transaction: 2ffef0e6c4d4628f2b1bea7c54c00142366d544bb27e0fd00572b10222258664
[2016-11-10 00:16:26][INFO] Block: 649997 (0.47s, hashes: L:ed719 / TX:7decf / M:cafed)
[2016-11-10 00:16:26][DEBUG] Checking that block 649998 is not an orphan.
[2016-11-10 00:16:26][DEBUG] Checking version.
[2016-11-10 00:16:27][DEBUG] Version check passed.
[2016-11-10 00:16:27][DEBUG] Skipping transaction: 0e6e41e8bb7dd0f640a699632c9f111a22348e8aa496ab16be60f6488cc908a8
[2016-11-10 00:16:27][INFO] Block: 649998 (0.51s, hashes: L:eba7b / TX:e17c7 / M:c769e)
[2016-11-10 00:16:27][DEBUG] Checking that block 649999 is not an orphan.
[2016-11-10 00:16:27][DEBUG] Checking version.
[2016-11-10 00:16:27][DEBUG] Version check passed.
[2016-11-10 00:16:27][DEBUG] Skipping transaction: a482662e2531c0974a52e48a78d256d4d8601dc518627698fcd8168f518b23af
[2016-11-10 00:16:27][INFO] Block: 649999 (0.50s, hashes: L:8e0c7 / TX:09972 / M:f7d98)
[2016-11-10 00:16:27][DEBUG] Checking that block 650000 is not an orphan.
[2016-11-10 00:16:27][DEBUG] Checking version.
[2016-11-10 00:16:28][DEBUG] Version check passed.
[2016-11-10 00:16:28][DEBUG] Skipping transaction: b6531e22d23fcbb19485f7488f7304e8ad23f141be50017287de20d9fdc50230
[2016-11-10 00:16:28][ERROR] Unhandled Exception

```

**Comment by unsystemizer** [comment]
I searched for `b6531e22d23fcbb19485f7488f7304e8ad23f141be50017287de20d9fdc50230` in:

* My existing Bitcoin Core instance on ARM system against which CP 9.55 on ARM works, but 9.55 from x64 doesn't:
```
{"result":"01000000010000000000000000000000000000000000000000000000000000000000000000ffffffff290310eb091c4d696e656420627920416e74506f6f6c201076842e2056a15dc505ab0000000037230000ffffffff0140be4025000000001976a9145b4723d03f932edce78330a8fb671397a1aaf5f988ac00000000","error":null,"id":null}
```

* My freshly downloaded Bitcoin Core on x64 system (once it's fully caught up I'll try CP 9.55 against it)
```{"result":null,"error":{"code":-5,"message":"No information available about transaction"},"id":null}```

**Comment by unsystemizer** [comment]
I ran into this again, with bootstrapped DB...
* v9.55.1
* addrindex 0.13.2 beta

**Comment by robby-dermody** [comment]
Sure I will do that later today.

**Comment by unsystemizer** [comment]
Robby mentioned that it's done. For block 649999 the hashes are different, but I don't know whether they're correct (I'm using 0.13.2 and I'm having some issues with it, as per #950). 
But FWIW, this is what I get on re-parse (v9.55.1 + addrindex 0.13.2 binary + freshly downloaded testnet blockchain).

```
2017-01-05-T15:10:05+0800 [INFO] Block (re-parse): 649999 (hashes: L:4e399 / TX:c62ea / M:5cc69)
2017-01-05-T15:10:05+0800 [INFO] Block (re-parse): 650000 (hashes: L:4d08c / TX:adae9 / M:abc4c)
```

**Comment by adamkrellenstein** [comment]
Being fixed.
