### ISSUE TITLE
Error start server

### ISSUE THREAD

**Issue by ecxotarama** [CounterpartyXCP/counterparty-lib#932]
Hello
I runing " sudo counterparty-server start " then error : 
```
[2016-10-10 14:53:22][INFO] Running v1.1.2 of counterparty-server.
[2016-10-10 14:53:22][INFO] Running v9.55.0 of counterparty-lib.
[2016-10-10 14:53:22][INFO] Acquiring lock.
[2016-10-10 14:53:22][INFO] Connecting to database.
[2016-10-10 14:53:22][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.2', 'console_scripts', 'counterparty-server')()
  File "/home/ubuntu/counterparty-cli-master/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/home/ubuntu/counterparty-cli-master/counterpartycli/server.py", line 139, in main
    db = init_with_catch(server.initialise, init_args)
  File "/home/ubuntu/counterparty-cli-master/counterpartycli/server.py", line 105, in init_with_catch
    return fn(**init_args)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.55.0-py3.4.egg/counterpartylib/server.py", line 79, in initialise
    return initialise_db()
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.55.0-py3.4.egg/counterpartylib/server.py", line 379, in initialise_db
    db = database.get_connection(read_only=False)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.55.0-py3.4.egg/counterpartylib/lib/database.py", line 83, in get_connection
    rows = list(cursor.execute('''PRAGMA foreign_key_check'''))
  File "src/cursor.c", line 990, in APSWCursor_execute.sqlite3_prepare
  File "src/statementcache.c", line 386, in sqlite3_prepare
apsw.CorruptError: CorruptError: malformed database schema (19aDsntGDgA99138b5FBWajqcc5sW4TUEQ) - near "send": syntax error
```
How i fix it ? Thanks

**Comment by unsystemizer** [comment]
CorruptError: malformed database schema => rebuild or download the database 
Check out `counterparty-server bootstrap`.
This doesn't seem to be a bug, but the way. Unless you can demonstrate it's a bug, please close this issue and use forums or the Counterparty Slack to ask questions.

**Comment by unsystemizer** [comment]
I tested everything including bootstrap, it works fine.
I haven't tried to let counterparty fully reparse the downloaded DB, but it does start and run fine (for well over 10 minutes). In your case the DB consistency error appears immediately, so it's different.
Maybe yesterday's copy of the bootstrap DB was corrupt. Let us know on Slack, thanks!
