### ISSUE TITLE
`--unconfirmed` doesn't work with issuance, but help suggests unconfirmed be used

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#933]
It seems either it should work, or else the CLI should be modified to not suggest a non-working workaround.
```
$ fednode exec counterparty-testnet counterparty-client issuance --source=mtfnbJ57W1u4zi15jFMpj8vqZ3jrN4jhVq --description=4d0d4eeb48cdca1d6d3cfb29f2e276ddca3ffe56b9e7a39767cd36a9f888419d --quantity=100 --asset=CPOA
[2016-10-16 00:08:23][INFO] Running v1.1.2 of counterparty-client.
ERROR:root:Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-client')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/counterparty-cli/counterpartycli/client.py", line 220, in main
    unsigned_hex = messages.compose(args.action, args)
  File "/counterparty-cli/counterpartycli/messages.py", line 278, in compose
    return compose_transaction(args, message, param_names)
  File "/counterparty-cli/counterpartycli/messages.py", line 269, in compose_transaction
    unsigned_tx_hex = util.api(method, params)
  File "/counterparty-cli/counterpartycli/util.py", line 92, in api
    return rpc(config.COUNTERPARTY_RPC, method, params=params, ssl_verify=config.COUNTERPARTY_RPC_SSL_VERIFY)
  File "/counterparty-cli/counterpartycli/util.py", line 89, in rpc
    raise RPCError('{}'.format(response_json['error']))
counterpartycli.util.RPCError: {'message': 'Error composing issuance transaction via API: Insufficient BTC at address mtfnbJ57W1u4zi15jFMpj8vqZ3jrN4jhVq. (Need approximately 0.00073861 BTC.) To spend unconfirmed coins, use the flag `--unconfirmed`. (Unconfirmed coins cannot be spent from multi‐sig addresses.)', 'code': -32001}
```

**Comment by unsystemizer** [comment]
Closing this - it turned out the reporter was hitting another bug (asset description too long, but that doesn't get caught so the final error is unrelated to the cause of this issue).
