### ISSUE TITLE
Issue with tiny dividend payment in BTC

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-lib#958]
It seems ([here](https://github.com/CounterpartyXCP/counterparty-lib/blob/9.55.1/counterpartylib/lib/messages/dividend.py#L142)) that dividends can be paid in BTC, but it doesn't work for me.

My address right now has this:
```
Asset        Balance
-------  -----------
BTC       0.10973178
DIVTEST  99.99900000
UTFFOUR   1.00000000
XCP       3.00000000
```

I'm the owner of DIVTEST and hold 99.999 out of the total float of 100.09. There's one guy who has less than 0.091 DIVTEST. I want to pay a dividend of 0.000001 BTC and this is what I get.

```
counterparty-client --source mofvU5ypG4CXBkgAZoUEcup9LkASr6V3eT --quantity-per-unit 0.000001 --asset DIVTEST --dividend-asset BTC
[2017-01-15 22:30:24][INFO] Running v1.1.2 of counterparty-client.
ERROR:root:Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 11, in <module>
    load_entry_point('counterparty-cli==1.1.2', 'console_scripts', 'counterparty-client')()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/client.py", line 220, in main
    unsigned_hex = messages.compose(args.action, args)
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/messages.py", line 278, in compose
    return compose_transaction(args, message, param_names)
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/messages.py", line 269, in compose_transaction
    unsigned_tx_hex = util.api(method, params)
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/util.py", line 92, in api
    return rpc(config.COUNTERPARTY_RPC, method, params=params, ssl_verify=config.COUNTERPARTY_RPC_SSL_VERIFY)
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/util.py", line 89, in rpc
    raise RPCError('{}'.format(response_json['error']))
counterpartycli.util.RPCError: {'code': -32001, 'message': "Error composing dividend transaction via API: ['zero dividend']"}
```

He wouldn't get rich - especially not on testnet - but that's still a nice sum (9 satoshi) and this isn't a "zero dividend".  0.000001 BTC per unit means the lucky DIVTEST owner should get `0.091 * 0.000001 = 0.000'000'091 BTC`.

I looked at the tests, there's no test for BTC dividends, by the way. 

Just FYI, XCP doesn't have this problem. If I use the exact same amount, just change to XCP, I do get an estimate for 9 "sats" as expected. The same applies for the asset itself (if I don't pay in another asset).

```
2017-01-15-T22:41:22+0800 [INFO] Total quantity to be distributed in dividends: 0.00000009 XCP
2017-01-15-T22:43:33+0800 [INFO] Total quantity to be distributed in dividends: 0.00000009 DIVTEST
```

If I bump the BTC dividend figure to  0.001 per each unit of DIVTEST, no error.

```
2017-01-15-T22:46:00+0800 [INFO] Total quantity to be distributed in dividends: 0.000091 BTC
```

**Comment by caydyan** [comment]
Opened PR #3347 to make the BTC dividend compose failure report the dust-threshold reason instead of the generic zero dividend error: https://github.com/CounterpartyXCP/counterparty-core/pull/3347

**Comment by caydyan** [comment]
Opened a `develop`-based replacement PR for this issue: https://github.com/CounterpartyXCP/counterparty-core/pull/3402

This carries the same focused fix as #3347, but targets `develop` so maintainers do not need to review the older `master`-based branch. It keeps BTC dividend behavior unchanged and only reports the dust-threshold reason instead of the generic `zero dividend` error.

BTC payout address if this qualifies for a contributor/security reward: `bc1qev5ant33v5y89qqjvcf4mh9hlax5svqf5xd7gc`

**Comment by ouziel-slama** [comment]
fixed here https://github.com/CounterpartyXCP/counterparty-core/pull/3402
