### ISSUE TITLE
Crash: Not all bytes consumed during deserialization

### ISSUE THREAD

**Issue by modulesio** [CounterpartyXCP/counterparty-lib#967]
Getting this running on testnet:

```
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-server')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/counterparty-cli/counterpartycli/server.py", line 157, in main
    server.start_all(db)
  File "/counterparty-lib/counterpartylib/server.py", line 408, in start_all
    blocks.follow(db)
  File "/counterparty-lib/counterpartylib/lib/blocks.py", line 1134, in follow
    current_cblock = backend.getblock(current_hash)
  File "/counterparty-lib/counterpartylib/lib/backend/__init__.py", line 49, in getblock
    return CBlock.deserialize(util.unhexlify(block_hex))
  File "/usr/local/lib/python3.5/dist-packages/bitcoin/core/serialize.py", line 120, in deserialize
    r, padding)
bitcoin.core.serialize.DeserializationExtraDataError: Not all bytes consumed during deserialization
```

I'm running `Bitcoin Core v0.13.2 addrindex`, `-testnet`, and `master` with this hash (currently latest): https://github.com/CounterpartyXCP/counterparty-lib/commit/113aa54fe246ae16eab9dea37212b263a3751e82

The server dies because of this.

**Comment by modulesio** [comment]
Does this have something to do with `bitcoin` package weirdness? Saw some messy stuff here: https://github.com/CounterpartyXCP/counterparty-lib/blob/master/docker/start.sh#L15
